(library
  (name middlend)
  (libraries util il)
  (modules
    sub
    totalize
    unthe
    sideconditions
    typefamilyremoval
    else
    undep
    utils
    deftorel
    subexpansion
    uncaseremoval
    aliasDemut
    improveids
    ite
    patSimp
    deftorel
    elsesimp
    letintromech
    datatypediet
    singlepatternmatch
  )
)
