import «wasm2.0»
import HelperLemmas

/-!
# Subtyping

Lean port of `spectec/test-rocq/theories/subtyping.v` (WASM value/result/
instruction-type subtyping: the width/depth + frame-rule machinery used
throughout the type-preservation proof).

Provenance: every declaration cites its Rocq source line number. Full
digest: `claude-logging/for-claude/digest_subtyping_and_extension_lemmas.md`.

The base relations `Valtype_sub`/`Resulttype_sub` are already generated by
the SpecTec Lean backend in `wasm2.0.lean` (confirmed: lines ~9418, 9424)
and match the inferred Rocq shape exactly (`Valtype_sub` has `refl`/`bot`
constructors; `Resulttype_sub` is `Forall₂ Valtype_sub` + equal length).
This file only needs to build `Resulttype_subtype`/`<ts:` (the
`List valtype`-level wrapper) and `instrtype_sub`/`<ti:` on top of them,
matching Rocq's `subtyping.v` exactly.

Phase 1 (this file, first pass): every signature stated, proofs `sorry`.
-/

namespace TLC

open scoped Classical -- harmless if unused; keeps room for classical proofs later

/-! ## Notation / core definitions (subtyping.v:1-27) -/

/-- Rocq: `Notation "tf1 :-> tf2" := (mk_functype (mk_list _ tf1) (mk_list _ tf2))`. -/
def mkFunctype (t1 t2 : List valtype) : functype := functype.mk_functype (.mk_list t1) (.mk_list t2)

/-- Rocq: `Notation "t1 <tv: t2" := (Valtype_sub t1 t2)`. Kept as a plain alias (not a
    notation) to avoid clashing with `<` on `Nat`-like types when this file is opened
    alongside others; call sites read `Valtype_sub t1 t2` directly, matching the underlying
    backend-generated relation name 1:1. -/
abbrev ValtypeSub := @Valtype_sub

/-- Rocq: `Definition Resulttype_subtype ts1 ts2 := Resulttype_sub (mk_list _ ts1) (mk_list _ ts2)`. -/
def ResulttypeSub (ts1 ts2 : List valtype) : Prop := Resulttype_sub (.mk_list ts1) (.mk_list ts2)

/-- Rocq: `Definition instrtype_sub tf tf' : Prop := match tf, tf' with ts11:->ts12, ts21:->ts22 =>
    exists ts_sub ts ts11_sub ts12_sup, ts21 = ts_sub++ts11_sub /\ ts22 = ts++ts12_sup /\
    (ts_sub<ts:ts) /\ (ts11_sub<ts:ts11) /\ (ts12<ts:ts12_sup) end`. -/
def instrtype_sub (tf tf' : functype) : Prop :=
  match tf, tf' with
  | .mk_functype (.mk_list ts11) (.mk_list ts12), .mk_functype (.mk_list ts21) (.mk_list ts22) =>
    ∃ ts_sub ts ts11_sub ts12_sup,
      ts21 = ts_sub ++ ts11_sub ∧
      ts22 = ts ++ ts12_sup ∧
      ResulttypeSub ts_sub ts ∧
      ResulttypeSub ts11_sub ts11 ∧
      ResulttypeSub ts12 ts12_sup

/-! ## Valtype subtyping — refl / trans / inversion (subtyping.v:33-77) -/

/-- Rocq `subtyping.v:33` `valtype_sub_refl`. Proof reused from a prior Lean session's
    `InstrtypeSub.lean`/`SeqTypingInversion.lean` (both have this identical proof). -/
theorem valtype_sub_refl (t : valtype) : Valtype_sub t t := Valtype_sub.refl t

/-- Rocq `subtyping.v:39` `valtype_sub_trans`. Proof reused from a prior Lean session
    (see above): the only non-`refl` case is `bot`, which concludes `Sub BOT c`
    unconditionally regardless of the middle term. -/
theorem valtype_sub_trans (t1 t2 t3 : valtype) :
    Valtype_sub t1 t2 → Valtype_sub t2 t3 → Valtype_sub t1 t3 := by
  intro h1 h2
  cases h1 with
  | refl _ => exact h2
  | bot _ => exact Valtype_sub.bot t3

/-- Rocq `subtyping.v:49` `valtype_sub_non_bot`. -/
theorem valtype_sub_non_bot (v v_valtype : valtype) :
    Valtype_sub v_valtype v → v_valtype ≠ valtype.BOT → v = v_valtype := by
  intro h hne
  cases h with
  | refl _ => rfl
  | bot _ => exact absurd rfl hne

/-- Rocq `subtyping.v:60` `resulttype_sub_non_bot`. Pointwise application of
    `valtype_sub_non_bot` across the zip, by induction on both lists together (using the
    length equality `ResulttypeSub` provides to keep them in lockstep). -/
theorem resulttype_sub_non_bot (v_ts v_ts2 : List valtype) :
    Forall (fun v_t => v_t ≠ valtype.BOT) v_ts → ResulttypeSub v_ts v_ts2 → v_ts = v_ts2 := by
  intro hnb h
  cases h with
  | mk_Resulttype_sub _ _ hlen hf =>
    have h2 : List.Forall₂ Valtype_sub v_ts v_ts2 := to_mathlib_forall₂ hlen hf
    clear hf hlen
    induction h2 with
    | nil => rfl
    | cons hval _ ih =>
      rename_i a b l1 l2 _
      have ha : a ≠ valtype.BOT := hnb a (by simp)
      have htail : Forall (fun v_t => v_t ≠ valtype.BOT) l1 := by
        intro x hx; exact hnb x (by simp [hx])
      have hb : b = a := valtype_sub_non_bot b a hval ha
      rw [hb, ih htail]

/-! ## Resulttype (list) subtyping — refl / size / trans / app-split (subtyping.v:79-347) -/

/-- New plumbing (no direct Rocq counterpart — `Forall2` is an inductive relation there,
    so reflexivity is a one-line induction; here `Forall₂` is a zip-based `def`, needing
    this explicit pointwise unfolding). Reused from a prior Lean session's
    `InstrtypeSub.lean`/`SeqTypingInversion.lean` (`forall2_valtype_sub_refl`). -/
theorem forall2_valtype_sub_refl (ts : List valtype) :
    Forall₂ (fun a b => Valtype_sub a b) ts ts := by
  induction ts with
  | nil => intro p hp; simp at hp
  | cons x xs ih =>
    intro p hp
    simp only [List.zip_cons_cons, List.mem_cons] at hp
    rcases hp with hp | hp
    · rw [hp]; exact valtype_sub_refl x
    · exact ih p hp

/-- New plumbing (see `forall2_valtype_sub_refl`). Reused from a prior Lean session
    (`forall2_valtype_sub_trans`). -/
theorem forall2_valtype_sub_trans {t1s t2s t3s : List valtype}
    (hlen12 : t1s.length = t2s.length) (hlen23 : t2s.length = t3s.length)
    (h1 : Forall₂ (fun a b => Valtype_sub a b) t1s t2s)
    (h2 : Forall₂ (fun a b => Valtype_sub a b) t2s t3s) :
    Forall₂ (fun a b => Valtype_sub a b) t1s t3s := by
  induction t1s generalizing t2s t3s with
  | nil =>
    match t2s, t3s, hlen12, hlen23 with
    | [], [], _, _ => intro p hp; simp at hp
  | cons x xs ih =>
    match t2s, hlen12 with
    | y :: ys, hlen12 =>
      match t3s, hlen23 with
      | z :: zs, hlen23 =>
        have hxy : Valtype_sub x y := h1 (x, y) (by simp)
        have hyz : Valtype_sub y z := h2 (y, z) (by simp)
        have hxz : Valtype_sub x z := valtype_sub_trans x y z hxy hyz
        have htail : Forall₂ (fun a b => Valtype_sub a b) xs zs := by
          apply ih (Nat.succ.inj hlen12) (Nat.succ.inj hlen23)
          · intro p hp; exact h1 p (by simp; right; exact hp)
          · intro p hp; exact h2 p (by simp; right; exact hp)
        intro p hp
        simp only [List.zip_cons_cons, List.mem_cons] at hp
        rcases hp with hp | hp
        · rw [hp]; exact hxz
        · exact htail p hp

/-- Rocq `subtyping.v:79` `resulttype_sub_refl`. Proof reused from a prior Lean session. -/
theorem resulttype_sub_refl (ts : List valtype) : ResulttypeSub ts ts :=
  Resulttype_sub.mk_Resulttype_sub ts ts rfl (forall2_valtype_sub_refl ts)

/-- Rocq `subtyping.v:88` `resulttype_sub_size_eq`. -/
theorem resulttype_sub_size_eq (ts1 ts2 : List valtype) :
    ResulttypeSub ts1 ts2 → ts1.length = ts2.length := by
  intro h; cases h with
  | mk_Resulttype_sub _ _ hlen _ => exact hlen

/-- Rocq `subtyping.v:97` `resulttype_sub_trans`. Proof reused from a prior Lean session. -/
theorem resulttype_sub_trans (ts1 ts2 ts3 : List valtype) :
    ResulttypeSub ts1 ts2 → ResulttypeSub ts2 ts3 → ResulttypeSub ts1 ts3 := by
  intro h1 h2
  cases h1 with
  | mk_Resulttype_sub _ _ hlen1 hf1 =>
    cases h2 with
    | mk_Resulttype_sub _ _ hlen2 hf2 =>
      exact Resulttype_sub.mk_Resulttype_sub ts1 ts3 (hlen1.trans hlen2)
        (forall2_valtype_sub_trans hlen1 hlen2 hf1 hf2)

-- `resulttype_sub_app_trans` (Rocq `subtyping.v:122`) is defined just below `resulttype_sub_app`
-- (`subtyping.v:188`), since its proof needs it.

/-- Rocq `subtyping.v:188` `resulttype_sub_app`. Proof reused from a prior Lean session. -/
theorem resulttype_sub_app (ts1_sub ts2_sub ts1 ts2 : List valtype) :
    ResulttypeSub ts1_sub ts1 → ResulttypeSub ts2_sub ts2 →
    ResulttypeSub (ts1_sub ++ ts2_sub) (ts1 ++ ts2) := by
  intro h1 h2
  cases h1 with
  | mk_Resulttype_sub _ _ hlen1 hf1 =>
    cases h2 with
    | mk_Resulttype_sub _ _ hlen2 hf2 =>
      refine Resulttype_sub.mk_Resulttype_sub (ts1_sub ++ ts2_sub) (ts1 ++ ts2) (by simp [hlen1, hlen2]) ?_
      have hzip := List.zip_append (l₁ := ts1_sub) (r₁ := ts2_sub) (l₂ := ts1) (r₂ := ts2) hlen1
      intro p hp
      rw [hzip] at hp
      rcases List.mem_append.mp hp with hp | hp
      · exact hf1 p hp
      · exact hf2 p hp

/-- Rocq `subtyping.v:122` `resulttype_sub_app_trans`. -/
theorem resulttype_sub_app_trans (ts_sub ts ts1 ts2 : List valtype) :
    ResulttypeSub ts_sub ts → ResulttypeSub (ts ++ ts1) ts2 → ResulttypeSub (ts_sub ++ ts1) ts2 := by
  intro h1 h2
  exact resulttype_sub_trans _ _ _ (resulttype_sub_app ts_sub ts1 ts ts1 h1 (resulttype_sub_refl ts1)) h2

/-- Rocq `subtyping.v:219` `Forall2_app'`. General list lemma, not subtyping-specific,
    but Rocq places it here (used to prove `resulttype_sub_app'` below). Converse of
    `List.zip_append`, same zip-splitting technique as `resulttype_sub_app`. -/
theorem Forall2_app' {α β : Type} (R : α → β → Prop) (l1 l2 : List α) (l1' l2' : List β) :
    l1.length = l1'.length → Forall₂ R (l1 ++ l2) (l1' ++ l2') →
    Forall₂ R l1 l1' ∧ Forall₂ R l2 l2' := by
  intro hlen h
  have hzip : (l1 ++ l2).zip (l1' ++ l2') = l1.zip l1' ++ l2.zip l2' := List.zip_append hlen
  refine ⟨?_, ?_⟩
  · intro p hp; exact h p (hzip ▸ List.mem_append.mpr (Or.inl hp))
  · intro p hp; exact h p (hzip ▸ List.mem_append.mpr (Or.inr hp))

/-- Rocq `subtyping.v:238` `resulttype_sub_app'`. Converse of `resulttype_sub_app`, same
    zip-splitting technique. -/
theorem resulttype_sub_app' (ts1_sub ts2_sub ts1 ts2 : List valtype) :
    ts1_sub.length = ts1.length → ResulttypeSub (ts1_sub ++ ts2_sub) (ts1 ++ ts2) →
    ResulttypeSub ts1_sub ts1 ∧ ResulttypeSub ts2_sub ts2 := by
  intro hlen1 h
  cases h with
  | mk_Resulttype_sub _ _ hlen hf =>
    have hlen2 : ts2_sub.length = ts2.length := by
      simp only [List.length_append] at hlen; omega
    obtain ⟨hf1, hf2⟩ := Forall2_app' _ ts1_sub ts2_sub ts1 ts2 hlen1 hf
    exact ⟨Resulttype_sub.mk_Resulttype_sub ts1_sub ts1 hlen1 hf1,
      Resulttype_sub.mk_Resulttype_sub ts2_sub ts2 hlen2 hf2⟩

/-- Rocq `subtyping.v:255` `Forall2_take`. Via `List.zip_eq_zipWith`/`List.take_zipWith`
    (Lean core), `(l1.take n).zip (l2.take n) = (l1.zip l2).take n`, then membership in a
    `take` implies membership in the original list. -/
theorem Forall2_take {α β : Type} (R : α → β → Prop) (l1 : List α) (l2 : List β) (n : Nat) :
    Forall₂ R l1 l2 → Forall₂ R (l1.take n) (l2.take n) := by
  intro h p hp
  have heq : (l1.take n).zip (l2.take n) = (l1.zip l2).take n := by
    simp [List.zip_eq_zipWith, List.take_zipWith]
  rw [heq] at hp
  exact h p (List.mem_of_mem_take hp)

/-- Rocq `subtyping.v:264` `Forall2_drop`. Dual of `Forall2_take` via `List.drop_zipWith`. -/
theorem Forall2_drop {α β : Type} (R : α → β → Prop) (l1 : List α) (l2 : List β) (n : Nat) :
    Forall₂ R l1 l2 → Forall₂ R (l1.drop n) (l2.drop n) := by
  intro h p hp
  have heq : (l1.drop n).zip (l2.drop n) = (l1.zip l2).drop n := by
    simp [List.zip_eq_zipWith, List.drop_zipWith]
  rw [heq] at hp
  exact h p (List.mem_of_mem_drop hp)

/-- Rocq `subtyping.v:273` `resulttype_sub_split`. -/
theorem resulttype_sub_split (ts1 ts2 : List valtype) (n : Nat) :
    ResulttypeSub ts1 ts2 → ResulttypeSub (ts1.take n) (ts2.take n) ∧ ResulttypeSub (ts1.drop n) (ts2.drop n) := by
  intro h
  cases h with
  | mk_Resulttype_sub _ _ hlen hf =>
    refine ⟨Resulttype_sub.mk_Resulttype_sub (ts1.take n) (ts2.take n) (by simp [hlen]) (Forall2_take _ ts1 ts2 n hf),
      Resulttype_sub.mk_Resulttype_sub (ts1.drop n) (ts2.drop n) (by simp [hlen]) (Forall2_drop _ ts1 ts2 n hf)⟩

-- `drop_size_cat`/`take_size_cat` (subtyping.v:297,307): Rocq's own comment calls these
-- duplicates kept "for compatibility reasons" — already ported in `HelperLemmas.lean`
-- (`TLC.drop_size_cat`, `TLC.take_size_cat`), reused here rather than redeclared.

/-- Rocq `subtyping.v:318` `resulttype_sub_split_sup`. Proof reused from a prior Lean
    session's `InstrtypeSub.lean` (adapted from its existential presentation to this
    file's `take`/`drop` presentation — same underlying `List.zip_append` argument). -/
theorem resulttype_sub_split_sup (ts ts1 ts2 : List valtype) :
    ResulttypeSub ts (ts1 ++ ts2) →
    ResulttypeSub (ts.take ts1.length) ts1 ∧ ResulttypeSub (ts.drop ts1.length) ts2 := by
  intro h
  cases h with
  | mk_Resulttype_sub _ _ hlen hf =>
    have hle : ts1.length ≤ ts.length := by
      simp only [List.length_append] at hlen; omega
    have hlent : ts1.length = (ts.take ts1.length).length := by simp [List.length_take, hle]
    have hzip : ts.zip (ts1 ++ ts2)
        = (ts.take ts1.length).zip ts1 ++ (ts.drop ts1.length).zip ts2 := by
      calc ts.zip (ts1 ++ ts2)
          = (ts.take ts1.length ++ ts.drop ts1.length).zip (ts1 ++ ts2) := by
            rw [List.take_append_drop]
        _ = (ts.take ts1.length).zip ts1 ++ (ts.drop ts1.length).zip ts2 := List.zip_append hlent.symm
    refine ⟨Resulttype_sub.mk_Resulttype_sub (ts.take ts1.length) ts1 hlent.symm ?_,
      Resulttype_sub.mk_Resulttype_sub (ts.drop ts1.length) ts2 ?_ ?_⟩
    · intro p hp
      exact hf p (hzip ▸ List.mem_append.mpr (Or.inl hp))
    · simp only [List.length_append] at hlen
      simp [List.length_drop]; omega
    · intro p hp
      exact hf p (hzip ▸ List.mem_append.mpr (Or.inr hp))

/-- Rocq `subtyping.v:334` `resulttype_sub_split_sup'`. Proof reused from a prior Lean
    session's `InstrtypeSub.lean` (its `resulttype_sub_split`, adapted to `take`/`drop`
    presentation). -/
theorem resulttype_sub_split_sup' (ts ts1 ts2 : List valtype) :
    ResulttypeSub (ts1 ++ ts2) ts →
    ResulttypeSub ts1 (ts.take ts1.length) ∧ ResulttypeSub ts2 (ts.drop ts1.length) := by
  intro h
  cases h with
  | mk_Resulttype_sub _ _ hlen hf =>
    have hle : ts1.length ≤ ts.length := by
      simp only [List.length_append] at hlen; omega
    have hlent : ts1.length = (ts.take ts1.length).length := by simp [List.length_take, hle]
    have hzip : (ts1 ++ ts2).zip ts
        = ts1.zip (ts.take ts1.length) ++ ts2.zip (ts.drop ts1.length) := by
      calc (ts1 ++ ts2).zip ts
          = (ts1 ++ ts2).zip (ts.take ts1.length ++ ts.drop ts1.length) := by
            rw [List.take_append_drop]
        _ = ts1.zip (ts.take ts1.length) ++ ts2.zip (ts.drop ts1.length) := List.zip_append hlent
    refine ⟨Resulttype_sub.mk_Resulttype_sub ts1 (ts.take ts1.length) hlent ?_,
      Resulttype_sub.mk_Resulttype_sub ts2 (ts.drop ts1.length) ?_ ?_⟩
    · intro p hp
      exact hf p (hzip ▸ List.mem_append.mpr (Or.inl hp))
    · simp only [List.length_append] at hlen
      simp [List.length_drop]; omega
    · intro p hp
      exact hf p (hzip ▸ List.mem_append.mpr (Or.inr hp))

/-! ## instrtype_sub core — reflexivity, transitivity (subtyping.v:349-460) -/

/-- Rocq `subtyping.v:349` `instrtype_sub_refl`. Proof reused from a prior Lean session's
    `InstrtypeSub.lean` — its `instrtype_sub` def (copied from `typing_lemmas.lean`) is
    field-for-field identical to this file's `instrtype_sub` up to variable renaming
    (`ts_sub`/`ts`/`ts11_sub`/`ts12_sup` here ↔ their `rest_in`/`rest_out`/`supplied_in`/
    `needed_out`), confirmed by direct comparison. -/
theorem instrtype_sub_refl (tf : functype) : instrtype_sub tf tf := by
  obtain ⟨t1, t2⟩ := tf
  obtain ⟨t1'⟩ := t1
  obtain ⟨t2'⟩ := t2
  refine ⟨[], [], t1', t2', rfl, rfl, ?_, ?_, ?_⟩
  · exact resulttype_sub_refl []
  · exact resulttype_sub_refl t1'
  · exact resulttype_sub_refl t2'

/-- Rocq `subtyping.v:363` `instrtype_sub_trans`. The hardest/longest proof in the file
    (~73 lines in Rocq, an explicit "sandwich" `take`/`drop` alignment argument). Proof
    reused from a prior Lean session's `InstrtypeSub.lean` (confirmed field-isomorphic
    `instrtype_sub`, see `instrtype_sub_refl` above), adapted from that file's existential
    presentation of `resulttype_sub_split_sup`/`_sup'` to this file's `take`/`drop`
    presentation (which matches Rocq's own statement more directly). -/
theorem instrtype_sub_trans (tf1 tf2 tf3 : functype) :
    instrtype_sub tf1 tf2 → instrtype_sub tf2 tf3 → instrtype_sub tf1 tf3 := by
  obtain ⟨oi1', oo1'⟩ := tf1
  obtain ⟨oi1⟩ := oi1'
  obtain ⟨oo1⟩ := oo1'
  obtain ⟨si2', no2'⟩ := tf2
  obtain ⟨si2⟩ := si2'
  obtain ⟨no2⟩ := no2'
  obtain ⟨si3', no3'⟩ := tf3
  obtain ⟨si3⟩ := si3'
  obtain ⟨no3⟩ := no3'
  intro h12 h23
  obtain ⟨rin12, rout12, sup12, nout12, hsi2, hno2, hrsub12, hsup12, hnout12⟩ := h12
  obtain ⟨rin23, rout23, sup23, nout23, hsi3, hno3, hrsub23, hsup23, hnout23⟩ := h23
  subst hsi2
  subst hno2
  obtain ⟨ha, hb⟩ := resulttype_sub_split_sup sup23 rin12 sup12 hsup23
  obtain ⟨hc, hd⟩ := resulttype_sub_split_sup' nout23 rout12 nout12 hnout23
  refine ⟨rin23 ++ (sup23.take rin12.length), rout23 ++ (nout23.take rout12.length),
    sup23.drop rin12.length, nout23.drop rout12.length, ?_, ?_, ?_, ?_, ?_⟩
  · rw [hsi3, List.append_assoc, List.take_append_drop]
  · rw [hno3, List.append_assoc, List.take_append_drop]
  · exact resulttype_sub_app _ _ _ _ hrsub23 (resulttype_sub_trans _ _ _ (resulttype_sub_trans _ _ _ ha hrsub12) hc)
  · exact resulttype_sub_trans _ _ _ hb hsup12
  · exact resulttype_sub_trans _ _ _ hnout12 hd

-- Rocq's 3 `PreOrder` typeclass instances (subtyping.v:439,447,455) are registered purely for
-- Coq's generalized-rewriting (`setoid_rewrite`) support; not load-bearing for any proof
-- content in this development and not ported — `_refl`/`_trans` above suffice.

/-! ## Empty-resulttype edge cases (subtyping.v:462-473) -/

/-- Rocq `subtyping.v:462` `resulttype_sub_empty`. -/
theorem resulttype_sub_empty (ts : List valtype) : ResulttypeSub ts [] → ts = [] := by
  intro h
  cases h with
  | mk_Resulttype_sub _ _ hlen _ => simpa using hlen

/-- Rocq `subtyping.v:473` `resulttype_empty_sub`. -/
theorem resulttype_empty_sub (ts : List valtype) : ResulttypeSub [] ts → ts = [] := by
  intro h
  cases h with
  | mk_Resulttype_sub _ _ hlen _ => simpa using hlen.symm

/-! ## instrtype_sub composition/algebra — the "frame rule" toolkit (subtyping.v:485-914) -/

/-- Rocq `subtyping.v:485` `instrtype_sub_compose`. -/
theorem instrtype_sub_compose (ts1 ts2 ts3 txs tys tzs : List valtype) :
    instrtype_sub (mkFunctype ts1 ts2) (mkFunctype txs tys) →
    instrtype_sub (mkFunctype ts2 ts3) (mkFunctype tys tzs) →
    instrtype_sub (mkFunctype ts1 ts3) (mkFunctype txs tzs) := by
  rintro ⟨tp1', tp1, ts1', ts2'', h1e1, h1e2, h1s1, h1s2, h1s3⟩
    ⟨tp2', tp2, ts2', ts3'', h2e1, h2e2, h2s1, h2s2, h2s3⟩
  subst h1e1; subst h1e2; subst h2e2
  -- `h2e1` was rewritten by the `subst h1e2` above: `tp1 ++ ts2'' = tp2' ++ ts2'`
  have h1s3' : ResulttypeSub (tp1' ++ ts2) (tp2' ++ ts2') := by
    rw [← h2e1]; exact resulttype_sub_app tp1' ts2 tp1 ts2'' h1s1 h1s3
  have h2s2' : ResulttypeSub (tp2' ++ ts2') (tp2 ++ ts2) := resulttype_sub_app tp2' ts2' tp2 ts2 h2s1 h2s2
  have hcomb : ResulttypeSub (tp1' ++ ts2) (tp2 ++ ts2) := resulttype_sub_trans _ _ _ h1s3' h2s2'
  have hlen : tp1'.length = tp2.length := by
    cases hcomb with
    | mk_Resulttype_sub _ _ hl _ =>
      simp only [List.length_append] at hl
      omega
  obtain ⟨h3, _⟩ := resulttype_sub_app' tp1' ts2 tp2 ts2 hlen hcomb
  exact ⟨tp1', tp2, ts1', ts3'', rfl, rfl, h3, h1s2, h2s3⟩

/-- Rocq `subtyping.v:510` `instrtype_sub_compose_le`. -/
theorem instrtype_sub_compose_le (ts1 ts2' ts2 ts3 ts4 txs tys tzs : List valtype) :
    instrtype_sub (mkFunctype ts1 ts2') (mkFunctype txs tys) →
    instrtype_sub (mkFunctype (ts3 ++ ts2) ts4) (mkFunctype tys tzs) →
    ts2.length = ts2'.length →
    instrtype_sub (mkFunctype (ts3 ++ ts1) ts4) (mkFunctype txs tzs) ∧ ResulttypeSub ts2' ts2 := by
  rintro ⟨tp1', tp1, ts1', ts2'', h1e1, h1e2, h1s1, h1s2, h1s3⟩
    ⟨tp2', tp2, ts3ts2', ts4'', h2e1, h2e2, h2s1, h2s2, h2s3⟩ hsize
  subst h1e1; subst h1e2; subst h2e2
  have h1s3' : ResulttypeSub (tp1' ++ ts2') (tp2' ++ ts3ts2') := by
    rw [← h2e1]; exact resulttype_sub_app tp1' ts2' tp1 ts2'' h1s1 h1s3
  have h2s2' : ResulttypeSub (tp2' ++ ts3ts2') (tp2 ++ (ts3 ++ ts2)) :=
    resulttype_sub_app tp2' ts3ts2' tp2 (ts3 ++ ts2) h2s1 h2s2
  have hcomb : ResulttypeSub (tp1' ++ ts2') ((tp2 ++ ts3) ++ ts2) := by
    rw [List.append_assoc]
    exact resulttype_sub_trans _ _ _ h1s3' h2s2'
  have hlen : tp1'.length = (tp2 ++ ts3).length := by
    cases hcomb with
    | mk_Resulttype_sub _ _ hl _ =>
      simp only [List.length_append] at hl ⊢
      omega
  obtain ⟨h3, h4⟩ := resulttype_sub_app' tp1' ts2' (tp2 ++ ts3) ts2 hlen hcomb
  refine ⟨?_, h4⟩
  obtain ⟨hA, hB⟩ := resulttype_sub_split_sup tp1' tp2 ts3 h3
  exact ⟨tp1'.take tp2.length, tp2, tp1'.drop tp2.length ++ ts1', ts4'',
    by rw [← List.append_assoc, List.take_append_drop], rfl, hA,
    resulttype_sub_app _ _ _ _ hB h1s2, h2s3⟩

/-- Rocq `subtyping.v:578` `instrtype_sub_compose_ge`. -/
theorem instrtype_sub_compose_ge (ts1 ts2 ts3' ts3 ts4 txs tys tzs : List valtype) :
    instrtype_sub (mkFunctype ts1 (ts2 ++ ts3')) (mkFunctype txs tys) →
    instrtype_sub (mkFunctype ts3 ts4) (mkFunctype tys tzs) →
    ts3.length = ts3'.length →
    instrtype_sub (mkFunctype ts1 (ts2 ++ ts4)) (mkFunctype txs tzs) ∧ ResulttypeSub ts3' ts3 := by
  rintro ⟨tp1', tp1, ts1', ts2ts3'', h1e1, h1e2, h1s1, h1s2, h1s3⟩
    ⟨tp2', tp2, ts3sub, ts4'', h2e1, h2e2, h2s1, h2s2, h2s3⟩ hsize
  subst h1e1; subst h1e2; subst h2e2
  have h1s3' : ResulttypeSub (tp1' ++ (ts2 ++ ts3')) (tp2' ++ ts3sub) := by
    rw [← h2e1]; exact resulttype_sub_app tp1' (ts2 ++ ts3') tp1 ts2ts3'' h1s1 h1s3
  have h2s2' : ResulttypeSub (tp2' ++ ts3sub) (tp2 ++ ts3) :=
    resulttype_sub_app tp2' ts3sub tp2 ts3 h2s1 h2s2
  have hcomb : ResulttypeSub ((tp1' ++ ts2) ++ ts3') (tp2 ++ ts3) := by
    rw [List.append_assoc]
    exact resulttype_sub_trans _ _ _ h1s3' h2s2'
  have hlen : (tp1' ++ ts2).length = tp2.length := by
    cases hcomb with
    | mk_Resulttype_sub _ _ hl _ =>
      simp only [List.length_append] at hl ⊢
      omega
  obtain ⟨h3, h4⟩ := resulttype_sub_app' (tp1' ++ ts2) ts3' tp2 ts3 hlen hcomb
  refine ⟨?_, h4⟩
  obtain ⟨h5, h6⟩ := resulttype_sub_split_sup' tp2 tp1' ts2 h3
  exact ⟨tp1', tp2.take tp1'.length, ts1', tp2.drop tp1'.length ++ ts4'',
    rfl, by rw [← List.append_assoc, List.take_append_drop], h5, h1s2,
    resulttype_sub_app _ _ _ _ h6 h2s3⟩

/-- Rocq `subtyping.v:636` `instrtype_sub_compose_eq`. -/
theorem instrtype_sub_compose_eq (ts1 ts2 ts2' ts3 txs tys tzs : List valtype) :
    instrtype_sub (mkFunctype ts1 ts2) (mkFunctype txs tys) →
    instrtype_sub (mkFunctype ts2' ts3) (mkFunctype tys tzs) →
    ts2.length = ts2'.length →
    instrtype_sub (mkFunctype ts1 ts3) (mkFunctype txs tzs) ∧ ResulttypeSub ts2 ts2' := by
  intro h1 h2 hsize
  have h2' : instrtype_sub (mkFunctype ([] ++ ts2') ts3) (mkFunctype tys tzs) := by simpa using h2
  obtain ⟨hfirst, hsecond⟩ := instrtype_sub_compose_le ts1 ts2 ts2' [] ts3 txs tys tzs h1 h2' hsize.symm
  exact ⟨by simpa using hfirst, hsecond⟩

/-- Rocq `subtyping.v:646` `instrtype_sub_compose_le'`. -/
theorem instrtype_sub_compose_le' (ts1 ts2 ts3 ts4 txs tys tzs : List valtype) :
    instrtype_sub (mkFunctype ts1 ts2) (mkFunctype txs tys) →
    instrtype_sub (mkFunctype ts3 ts4) (mkFunctype tys tzs) →
    ts2.length ≤ ts3.length →
    instrtype_sub (mkFunctype ((ts3.take (ts3.length - ts2.length)) ++ ts1) ts4) (mkFunctype txs tzs) ∧
      ResulttypeSub ts2 (ts3.drop (ts3.length - ts2.length)) := by
  intro h1 h2 hsize
  have hsplit : ts3 = ts3.take (ts3.length - ts2.length) ++ ts3.drop (ts3.length - ts2.length) :=
    (List.take_append_drop _ _).symm
  have h2' : instrtype_sub
      (mkFunctype (ts3.take (ts3.length - ts2.length) ++ ts3.drop (ts3.length - ts2.length)) ts4)
      (mkFunctype tys tzs) := by rw [← hsplit]; exact h2
  have hlensuf : (ts3.drop (ts3.length - ts2.length)).length = ts2.length := by
    simp only [List.length_drop]; omega
  exact instrtype_sub_compose_le ts1 ts2 (ts3.drop (ts3.length - ts2.length))
    (ts3.take (ts3.length - ts2.length)) ts4 txs tys tzs h1 h2' hlensuf

/-- Rocq `subtyping.v:662` `instrtype_sub_compose_ge'`. -/
theorem instrtype_sub_compose_ge' (ts1 ts2 ts3 ts4 txs tys tzs : List valtype) :
    instrtype_sub (mkFunctype ts1 ts2) (mkFunctype txs tys) →
    instrtype_sub (mkFunctype ts3 ts4) (mkFunctype tys tzs) →
    ts3.length ≤ ts2.length →
    instrtype_sub (mkFunctype ts1 ((ts2.take (ts2.length - ts3.length)) ++ ts4)) (mkFunctype txs tzs) ∧
      ResulttypeSub (ts2.drop (ts2.length - ts3.length)) ts3 := by
  intro h1 h2 hsize
  have hsplit : ts2 = ts2.take (ts2.length - ts3.length) ++ ts2.drop (ts2.length - ts3.length) :=
    (List.take_append_drop _ _).symm
  have h1' : instrtype_sub
      (mkFunctype ts1 (ts2.take (ts2.length - ts3.length) ++ ts2.drop (ts2.length - ts3.length)))
      (mkFunctype txs tys) := by rw [← hsplit]; exact h1
  have hlensuf : ts3.length = (ts2.drop (ts2.length - ts3.length)).length := by
    simp only [List.length_drop]; omega
  exact instrtype_sub_compose_ge ts1 (ts2.take (ts2.length - ts3.length))
    (ts2.drop (ts2.length - ts3.length)) ts3 ts4 txs tys tzs h1' h2 hlensuf

/-- Rocq `subtyping.v:679` `instrtype_sub_compose1`. -/
theorem instrtype_sub_compose1 (ts1 ts2 ts3 ts4 txs tys tzs : List valtype) :
    instrtype_sub (mkFunctype ts1 ts2) (mkFunctype txs tys) →
    instrtype_sub (mkFunctype (ts3 ++ ts2) ts4) (mkFunctype tys tzs) →
    instrtype_sub (mkFunctype (ts3 ++ ts1) ts4) (mkFunctype txs tzs) := by
  intro h1 h2
  exact (instrtype_sub_compose_le ts1 ts2 ts2 ts3 ts4 txs tys tzs h1 h2 rfl).1

/-- Rocq `subtyping.v:688` `instrtype_sub_compose0`. Semantically identical to
    `instrtype_sub_compose` above (Rocq derives it via `compose1` instead, kept separate
    for call-site naming fidelity). -/
theorem instrtype_sub_compose0 (ts1 ts2 ts3 txs tys tzs : List valtype) :
    instrtype_sub (mkFunctype ts1 ts2) (mkFunctype txs tys) →
    instrtype_sub (mkFunctype ts2 ts3) (mkFunctype tys tzs) →
    instrtype_sub (mkFunctype ts1 ts3) (mkFunctype txs tzs) := by
  intro h1 h2
  have h2' : instrtype_sub (mkFunctype ([] ++ ts2) ts3) (mkFunctype tys tzs) := by simpa using h2
  have := instrtype_sub_compose1 ts1 ts2 [] ts3 txs tys tzs h1 h2'
  simpa using this

/-- Rocq `subtyping.v:697` `instrtype_sub_compose2`. -/
theorem instrtype_sub_compose2 (ts1 ts2 ts3 ts4 txs tys tzs : List valtype) :
    instrtype_sub (mkFunctype ts1 (ts2 ++ ts3)) (mkFunctype txs tys) →
    instrtype_sub (mkFunctype ts3 ts4) (mkFunctype tys tzs) →
    instrtype_sub (mkFunctype ts1 (ts2 ++ ts4)) (mkFunctype txs tzs) := by
  intro h1 h2
  exact (instrtype_sub_compose_ge ts1 ts2 ts3 ts3 ts4 txs tys tzs h1 h2 rfl).1

/-- Rocq `subtyping.v:706` `instrtype_sub_cancel_left`. -/
theorem instrtype_sub_cancel_left (t : valtype) (ts1 ts2 txs tys : List valtype) :
    instrtype_sub (mkFunctype (t :: ts1) (t :: ts2)) (mkFunctype txs tys) →
    instrtype_sub (mkFunctype ts1 ts2) (mkFunctype txs tys) := by
  intro h1
  have hframe : instrtype_sub (mkFunctype ts1 ts2) (mkFunctype (t :: ts1) (t :: ts2)) :=
    ⟨[t], [t], ts1, ts2, rfl, rfl, resulttype_sub_refl [t], resulttype_sub_refl ts1, resulttype_sub_refl ts2⟩
  exact instrtype_sub_trans _ _ _ hframe h1

/-- Rocq `subtyping.v:720` `instrtype_sub_empty`. -/
theorem instrtype_sub_empty (txs tys : List valtype) :
    instrtype_sub (mkFunctype [] []) (mkFunctype txs tys) → ResulttypeSub txs tys := by
  rintro ⟨tp1', tp1, ts1', ts2'', h1e1, h1e2, h1s1, h1s2, h1s3⟩
  subst h1e1; subst h1e2
  exact resulttype_sub_app tp1' ts1' tp1 ts2'' h1s1 (resulttype_sub_trans _ _ _ h1s2 h1s3)

/-- Rocq `subtyping.v:732` `instrtype_sub_sub_empty`. -/
theorem instrtype_sub_sub_empty (txs tys : List valtype) :
    instrtype_sub (mkFunctype txs tys) (mkFunctype [] []) → txs = [] ∧ tys = [] := by
  rintro ⟨tp1', tp1, ts1', ts2'', h1e1, h1e2, h1s1, h1s2, h1s3⟩
  have e1 : tp1' = [] ∧ ts1' = [] := List.append_eq_nil_iff.mp h1e1.symm
  have e2 : tp1 = [] ∧ ts2'' = [] := List.append_eq_nil_iff.mp h1e2.symm
  rw [e1.2] at h1s2
  rw [e2.2] at h1s3
  exact ⟨resulttype_empty_sub txs h1s2, resulttype_sub_empty tys h1s3⟩

/-- Rocq `subtyping.v:747` `instrtype_sub_sub_empty1`. -/
theorem instrtype_sub_sub_empty1 (txs tys tzs : List valtype) :
    instrtype_sub (mkFunctype txs tys) (mkFunctype [] tzs) → txs = [] ∧ ResulttypeSub tys tzs := by
  rintro ⟨tp1', tp1, ts1', ts2'', h1e1, h1e2, h1s1, h1s2, h1s3⟩
  have e1 : tp1' = [] ∧ ts1' = [] := List.append_eq_nil_iff.mp h1e1.symm
  rw [e1.1] at h1s1
  have etp1 : tp1 = [] := resulttype_empty_sub tp1 h1s1
  rw [e1.2] at h1s2
  have etxs : txs = [] := resulttype_empty_sub txs h1s2
  refine ⟨etxs, ?_⟩
  rw [etp1, List.nil_append] at h1e2
  rw [h1e2]; exact h1s3

/-- Rocq `subtyping.v:761` `instrtype_sub_sub_empty2`. -/
theorem instrtype_sub_sub_empty2 (txs tys tzs : List valtype) :
    instrtype_sub (mkFunctype txs tys) (mkFunctype tzs []) → tys = [] ∧ ResulttypeSub tzs txs := by
  rintro ⟨tp1', tp1, ts1', ts2'', h1e1, h1e2, h1s1, h1s2, h1s3⟩
  have e2 : tp1 = [] ∧ ts2'' = [] := List.append_eq_nil_iff.mp h1e2.symm
  rw [e2.1] at h1s1
  have etp1' : tp1' = [] := resulttype_sub_empty tp1' h1s1
  rw [e2.2] at h1s3
  have etys : tys = [] := resulttype_sub_empty tys h1s3
  refine ⟨etys, ?_⟩
  rw [etp1', List.nil_append] at h1e1
  rw [h1e1]; exact h1s2

/-- Rocq `subtyping.v:775` `instrtype_sub_iff_resulttype_sub`. -/
theorem instrtype_sub_iff_resulttype_sub (ts1 ts2 ts3 : List valtype) :
    ResulttypeSub ts1 ts2 ↔ instrtype_sub (mkFunctype ts3 ts1) (mkFunctype ts3 ts2) := by
  constructor
  · intro h
    exact ⟨[], [], ts3, ts2, by simp, by simp, resulttype_sub_refl [], resulttype_sub_refl ts3, h⟩
  · rintro ⟨tp1', tp1, ts1', ts2'', h1e1, h1e2, h1s1, h1s2, h1s3⟩
    have htp1'_len : tp1'.length = 0 := by
      have h1s2' : ResulttypeSub ts1' (tp1' ++ ts1') := h1e1 ▸ h1s2
      cases h1s2' with
      | mk_Resulttype_sub _ _ hlen _ =>
        simp only [List.length_append] at hlen
        omega
    have htp1' : tp1' = [] := List.length_eq_zero_iff.mp htp1'_len
    have htp1 : tp1 = [] := resulttype_empty_sub tp1 (htp1' ▸ h1s1)
    have he2 : ts2 = ts2'' := by rw [h1e2, htp1, List.nil_append]
    rw [he2]
    exact h1s3

/-- Rocq `subtyping.v:807` `instrtype_sub_iff_resulttype_sub'`. -/
theorem instrtype_sub_iff_resulttype_sub' (ts1 ts2 ts3 : List valtype) :
    ResulttypeSub ts1 ts2 ↔ instrtype_sub (mkFunctype ts2 ts3) (mkFunctype ts1 ts3) := by
  constructor
  · intro h
    exact ⟨[], [], ts1, ts3, by simp, by simp, resulttype_sub_refl [], h, resulttype_sub_refl ts3⟩
  · rintro ⟨tp1', tp1, ts1', ts2'', h1e1, h1e2, h1s1, h1s2, h1s3⟩
    have htp1_len : tp1.length = 0 := by
      have h1s3' : ResulttypeSub (tp1 ++ ts2'') ts2'' := h1e2 ▸ h1s3
      cases h1s3' with
      | mk_Resulttype_sub _ _ hlen _ =>
        simp only [List.length_append] at hlen
        omega
    have htp1 : tp1 = [] := List.length_eq_zero_iff.mp htp1_len
    have htp1' : tp1' = [] := resulttype_sub_empty tp1' (htp1 ▸ h1s1)
    rw [h1e1, htp1', List.nil_append]
    exact h1s2

/-- Rocq `subtyping.v:837` `instrtype_sub_extend`. Rocq's own proof chains through
    `instrtype_sub_compose_le` with an auxiliary `instrtype_sub_refl (tys->tzs)` fact and
    some `N`-arithmetic bookkeeping specific to relating `tys`'s length to `t2s`'s; ported
    here via a more direct route to the same witness (`t3s := ts`, the *original* Hsub's own
    "unrelated frame" witness), since the only real content needed is
    `ResulttypeSub txs (ts ++ t1s)`, built directly from `resulttype_sub_app`. -/
theorem instrtype_sub_extend (t1s t2s txs tys tzs : List valtype) :
    instrtype_sub (mkFunctype t1s t2s) (mkFunctype txs tys) →
    ∃ t3s, instrtype_sub (mkFunctype (t3s ++ t1s) tzs) (mkFunctype txs tzs) := by
  rintro ⟨ts', ts, t1s', t2s', h1, h2, h3, h4, h5⟩
  refine ⟨ts, [], [], txs, tzs, rfl, rfl, resulttype_sub_refl [], ?_, resulttype_sub_refl tzs⟩
  rw [h1]
  exact resulttype_sub_app ts' t1s' ts t1s h3 h4

/-- Rocq `subtyping.v:856` `instrtype_sub_add_same`. The explicit "frame rule" lemma. -/
theorem instrtype_sub_add_same (ts1 ts2 ts3 : List valtype) :
    instrtype_sub (mkFunctype ts1 ts2) (mkFunctype (ts3 ++ ts1) (ts3 ++ ts2)) :=
  ⟨ts3, ts3, ts1, ts2, rfl, rfl, resulttype_sub_refl ts3, resulttype_sub_refl ts1, resulttype_sub_refl ts2⟩

/-- Rocq `subtyping.v:867` `resulttype_sub_cons`. -/
theorem resulttype_sub_cons (t t' : valtype) (ts ts' : List valtype) :
    ResulttypeSub (t :: ts) (t' :: ts') → Valtype_sub t t' ∧ ResulttypeSub ts ts' := by
  intro h
  cases h with
  | mk_Resulttype_sub _ _ hlen hf =>
    have hzip : (t :: ts).zip (t' :: ts') = (t, t') :: ts.zip ts' := rfl
    refine ⟨hf (t, t') (hzip ▸ List.mem_cons_self ..), ?_⟩
    refine Resulttype_sub.mk_Resulttype_sub ts ts' (by simpa using hlen) ?_
    intro p hp
    exact hf p (hzip ▸ List.mem_cons_of_mem _ hp)

/-- Rocq `subtyping.v:878` `instr_subtyping_strengthen2`. Mirror image of
    `instr_subtyping_weaken2` below (strengthens the *input* side via
    `resulttype_sub_split_sup` instead of weakening the *output* side via
    `resulttype_sub_split_sup'`) — proved directly by the same technique
    rather than ported from a prior session, since the dual proof is a
    one-for-one transcription once `instr_subtyping_weaken2`'s shape is
    understood. -/
theorem instr_subtyping_strengthen2 (tx1 ty1 tx2 ty2 ts : List valtype) :
    instrtype_sub (mkFunctype tx1 ty1) (mkFunctype tx2 ty2) → ResulttypeSub ts tx2 →
    instrtype_sub (mkFunctype tx1 ty1) (mkFunctype ts ty2) := by
  intro h hy
  obtain ⟨rin, rout, sup, nout, htx2, hty2, hrsub, hsup, hnout⟩ := h
  subst htx2
  obtain ⟨hrin', hsup'⟩ := resulttype_sub_split_sup ts rin sup hy
  refine ⟨ts.take rin.length, rout, ts.drop rin.length, nout,
    (List.take_append_drop rin.length ts).symm, hty2,
    resulttype_sub_trans _ _ _ hrin' hrsub, resulttype_sub_trans _ _ _ hsup' hsup, hnout⟩

/-- Rocq `subtyping.v:898` (last declaration in file) `instr_subtyping_weaken2`. Already
    proved (0 sorry) in a previous session's `InstrtypeSub.lean` — see
    `claude-logging/for-claude/digest_prior_lean_attempts.md` §1D — this was one of the
    prior `typing_lemmas.lean`'s 4 open `sorry`s; worth porting that proof once definitions
    are confirmed aligned. -/
theorem instr_subtyping_weaken2 (tx1 ty1 tx2 ty2 ts : List valtype) :
    instrtype_sub (mkFunctype tx1 ty1) (mkFunctype tx2 ty2) → ResulttypeSub ty2 ts →
    instrtype_sub (mkFunctype tx1 ty1) (mkFunctype tx2 ts) := by
  intro h hy
  obtain ⟨rin, rout, sup, nout, htx2, hty2, hrsub, hsup, hnout⟩ := h
  subst hty2
  obtain ⟨hrout', hnout'⟩ := resulttype_sub_split_sup' ts rout nout hy
  refine ⟨rin, ts.take rout.length, sup, ts.drop rout.length, htx2,
    (List.take_append_drop rout.length ts).symm,
    resulttype_sub_trans _ _ _ hrsub hrout', hsup,
    resulttype_sub_trans _ _ _ hnout hnout'⟩

end TLC
