import «wasm2.0»
import HelperLemmas

/-!
# Subtyping

Lean port of `spectec/test-rocq/theories/subtyping.v` (WASM value/result/
instruction-type subtyping: the width/depth + frame-rule machinery used
throughout the type-preservation proof).

Provenance: every declaration cites its Rocq source line number. Full
digest: `claude-logging/for-claude/digest_subtyping_and_extension_lemmas.md`.

The base relations `Valtype_sub`/`Resulttype_sub` are already generated by
the SpecTec Lean backend in `wasm2.0.lean` (confirmed: lines ~9418, 9424)
and match the inferred Rocq shape exactly (`Valtype_sub` has `refl`/`bot`
constructors; `Resulttype_sub` is `Forall₂ Valtype_sub` + equal length).
This file only needs to build `Resulttype_subtype`/`<ts:` (the
`List valtype`-level wrapper) and `instrtype_sub`/`<ti:` on top of them,
matching Rocq's `subtyping.v` exactly.

Phase 1 (this file, first pass): every signature stated, proofs `sorry`.
-/

namespace TLC

open scoped Classical -- harmless if unused; keeps room for classical proofs later

/-! ## Notation / core definitions (subtyping.v:1-27) -/

/-- Rocq: `Notation "tf1 :-> tf2" := (mk_functype (mk_list _ tf1) (mk_list _ tf2))`. -/
def mkFunctype (t1 t2 : List valtype) : functype := functype.mk_functype (.mk_list t1) (.mk_list t2)

/-- Rocq: `Notation "t1 <tv: t2" := (Valtype_sub t1 t2)`. Kept as a plain alias (not a
    notation) to avoid clashing with `<` on `Nat`-like types when this file is opened
    alongside others; call sites read `Valtype_sub t1 t2` directly, matching the underlying
    backend-generated relation name 1:1. -/
abbrev ValtypeSub := @Valtype_sub

/-- Rocq: `Definition Resulttype_subtype ts1 ts2 := Resulttype_sub (mk_list _ ts1) (mk_list _ ts2)`. -/
def ResulttypeSub (ts1 ts2 : List valtype) : Prop := Resulttype_sub (.mk_list ts1) (.mk_list ts2)

/-- Rocq: `Definition instrtype_sub tf tf' : Prop := match tf, tf' with ts11:->ts12, ts21:->ts22 =>
    exists ts_sub ts ts11_sub ts12_sup, ts21 = ts_sub++ts11_sub /\ ts22 = ts++ts12_sup /\
    (ts_sub<ts:ts) /\ (ts11_sub<ts:ts11) /\ (ts12<ts:ts12_sup) end`. -/
def instrtype_sub (tf tf' : functype) : Prop :=
  match tf, tf' with
  | .mk_functype (.mk_list ts11) (.mk_list ts12), .mk_functype (.mk_list ts21) (.mk_list ts22) =>
    ∃ ts_sub ts ts11_sub ts12_sup,
      ts21 = ts_sub ++ ts11_sub ∧
      ts22 = ts ++ ts12_sup ∧
      ResulttypeSub ts_sub ts ∧
      ResulttypeSub ts11_sub ts11 ∧
      ResulttypeSub ts12 ts12_sup

/-! ## Valtype subtyping — refl / trans / inversion (subtyping.v:33-77) -/

/-- Rocq `subtyping.v:33` `valtype_sub_refl`. -/
theorem valtype_sub_refl (t : valtype) : Valtype_sub t t := sorry

/-- Rocq `subtyping.v:39` `valtype_sub_trans`. -/
theorem valtype_sub_trans (t1 t2 t3 : valtype) :
    Valtype_sub t1 t2 → Valtype_sub t2 t3 → Valtype_sub t1 t3 := sorry

/-- Rocq `subtyping.v:49` `valtype_sub_non_bot`. -/
theorem valtype_sub_non_bot (v v_valtype : valtype) :
    Valtype_sub v_valtype v → v_valtype ≠ valtype.BOT → v = v_valtype := sorry

/-- Rocq `subtyping.v:60` `resulttype_sub_non_bot`. -/
theorem resulttype_sub_non_bot (v_ts v_ts2 : List valtype) :
    Forall (fun v_t => v_t ≠ valtype.BOT) v_ts → ResulttypeSub v_ts v_ts2 → v_ts = v_ts2 := sorry

/-! ## Resulttype (list) subtyping — refl / size / trans / app-split (subtyping.v:79-347) -/

/-- Rocq `subtyping.v:79` `resulttype_sub_refl`. -/
theorem resulttype_sub_refl (ts : List valtype) : ResulttypeSub ts ts := sorry

/-- Rocq `subtyping.v:88` `resulttype_sub_size_eq`. -/
theorem resulttype_sub_size_eq (ts1 ts2 : List valtype) :
    ResulttypeSub ts1 ts2 → ts1.length = ts2.length := sorry

/-- Rocq `subtyping.v:97` `resulttype_sub_trans`. -/
theorem resulttype_sub_trans (ts1 ts2 ts3 : List valtype) :
    ResulttypeSub ts1 ts2 → ResulttypeSub ts2 ts3 → ResulttypeSub ts1 ts3 := sorry

/-- Rocq `subtyping.v:122` `resulttype_sub_app_trans`. -/
theorem resulttype_sub_app_trans (ts_sub ts ts1 ts2 : List valtype) :
    ResulttypeSub ts_sub ts → ResulttypeSub (ts ++ ts1) ts2 → ResulttypeSub (ts_sub ++ ts1) ts2 := sorry

/-- Rocq `subtyping.v:188` `resulttype_sub_app`. -/
theorem resulttype_sub_app (ts1_sub ts2_sub ts1 ts2 : List valtype) :
    ResulttypeSub ts1_sub ts1 → ResulttypeSub ts2_sub ts2 →
    ResulttypeSub (ts1_sub ++ ts2_sub) (ts1 ++ ts2) := sorry

/-- Rocq `subtyping.v:219` `Forall2_app'`. General list lemma, not subtyping-specific,
    but Rocq places it here (used to prove `resulttype_sub_app'` below). -/
theorem Forall2_app' {α β : Type} (R : α → β → Prop) (l1 l2 : List α) (l1' l2' : List β) :
    l1.length = l1'.length → Forall₂ R (l1 ++ l2) (l1' ++ l2') →
    Forall₂ R l1 l1' ∧ Forall₂ R l2 l2' := sorry

/-- Rocq `subtyping.v:238` `resulttype_sub_app'`. -/
theorem resulttype_sub_app' (ts1_sub ts2_sub ts1 ts2 : List valtype) :
    ts1_sub.length = ts1.length → ResulttypeSub (ts1_sub ++ ts2_sub) (ts1 ++ ts2) →
    ResulttypeSub ts1_sub ts1 ∧ ResulttypeSub ts2_sub ts2 := sorry

/-- Rocq `subtyping.v:255` `Forall2_take`. -/
theorem Forall2_take {α β : Type} (R : α → β → Prop) (l1 : List α) (l2 : List β) (n : Nat) :
    Forall₂ R l1 l2 → Forall₂ R (l1.take n) (l2.take n) := sorry

/-- Rocq `subtyping.v:264` `Forall2_drop`. -/
theorem Forall2_drop {α β : Type} (R : α → β → Prop) (l1 : List α) (l2 : List β) (n : Nat) :
    Forall₂ R l1 l2 → Forall₂ R (l1.drop n) (l2.drop n) := sorry

/-- Rocq `subtyping.v:273` `resulttype_sub_split`. -/
theorem resulttype_sub_split (ts1 ts2 : List valtype) (n : Nat) :
    ResulttypeSub ts1 ts2 → ResulttypeSub (ts1.take n) (ts2.take n) ∧ ResulttypeSub (ts1.drop n) (ts2.drop n) := sorry

-- `drop_size_cat`/`take_size_cat` (subtyping.v:297,307): Rocq's own comment calls these
-- duplicates kept "for compatibility reasons" — already ported in `HelperLemmas.lean`
-- (`TLC.drop_size_cat`, `TLC.take_size_cat`), reused here rather than redeclared.

/-- Rocq `subtyping.v:318` `resulttype_sub_split_sup`. -/
theorem resulttype_sub_split_sup (ts ts1 ts2 : List valtype) :
    ResulttypeSub ts (ts1 ++ ts2) →
    ResulttypeSub (ts.take ts1.length) ts1 ∧ ResulttypeSub (ts.drop ts1.length) ts2 := sorry

/-- Rocq `subtyping.v:334` `resulttype_sub_split_sup'`. -/
theorem resulttype_sub_split_sup' (ts ts1 ts2 : List valtype) :
    ResulttypeSub (ts1 ++ ts2) ts →
    ResulttypeSub ts1 (ts.take ts1.length) ∧ ResulttypeSub ts2 (ts.drop ts1.length) := sorry

/-! ## instrtype_sub core — reflexivity, transitivity (subtyping.v:349-460) -/

/-- Rocq `subtyping.v:349` `instrtype_sub_refl`. -/
theorem instrtype_sub_refl (tf : functype) : instrtype_sub tf tf := sorry

/-- Rocq `subtyping.v:363` `instrtype_sub_trans`. The hardest/longest proof in the file
    (~73 lines in Rocq, an explicit "sandwich" `take`/`drop` alignment argument). A
    previous session's `InstrtypeSub.lean` already has a complete (0-`sorry`) Lean proof of
    this exact statement (against an equivalent `instrtype_sub` definition) — see
    `claude-logging/for-claude/digest_prior_lean_attempts.md` — worth reusing once the
    definitions are confirmed to line up field-for-field. -/
theorem instrtype_sub_trans (tf1 tf2 tf3 : functype) :
    instrtype_sub tf1 tf2 → instrtype_sub tf2 tf3 → instrtype_sub tf1 tf3 := sorry

-- Rocq's 3 `PreOrder` typeclass instances (subtyping.v:439,447,455) are registered purely for
-- Coq's generalized-rewriting (`setoid_rewrite`) support; not load-bearing for any proof
-- content in this development and not ported — `_refl`/`_trans` above suffice.

/-! ## Empty-resulttype edge cases (subtyping.v:462-473) -/

/-- Rocq `subtyping.v:462` `resulttype_sub_empty`. -/
theorem resulttype_sub_empty (ts : List valtype) : ResulttypeSub ts [] → ts = [] := sorry

/-- Rocq `subtyping.v:473` `resulttype_empty_sub`. -/
theorem resulttype_empty_sub (ts : List valtype) : ResulttypeSub [] ts → ts = [] := sorry

/-! ## instrtype_sub composition/algebra — the "frame rule" toolkit (subtyping.v:485-914) -/

/-- Rocq `subtyping.v:485` `instrtype_sub_compose`. -/
theorem instrtype_sub_compose (ts1 ts2 ts3 txs tys tzs : List valtype) :
    instrtype_sub (mkFunctype ts1 ts2) (mkFunctype txs tys) →
    instrtype_sub (mkFunctype ts2 ts3) (mkFunctype tys tzs) →
    instrtype_sub (mkFunctype ts1 ts3) (mkFunctype txs tzs) := sorry

/-- Rocq `subtyping.v:510` `instrtype_sub_compose_le`. -/
theorem instrtype_sub_compose_le (ts1 ts2' ts2 ts3 ts4 txs tys tzs : List valtype) :
    instrtype_sub (mkFunctype ts1 ts2') (mkFunctype txs tys) →
    instrtype_sub (mkFunctype (ts3 ++ ts2) ts4) (mkFunctype tys tzs) →
    ts2.length = ts2'.length →
    instrtype_sub (mkFunctype (ts3 ++ ts1) ts4) (mkFunctype txs tzs) ∧ ResulttypeSub ts2' ts2 := sorry

/-- Rocq `subtyping.v:578` `instrtype_sub_compose_ge`. -/
theorem instrtype_sub_compose_ge (ts1 ts2 ts3' ts3 ts4 txs tys tzs : List valtype) :
    instrtype_sub (mkFunctype ts1 (ts2 ++ ts3')) (mkFunctype txs tys) →
    instrtype_sub (mkFunctype ts3 ts4) (mkFunctype tys tzs) →
    ts3.length = ts3'.length →
    instrtype_sub (mkFunctype ts1 (ts2 ++ ts4)) (mkFunctype txs tzs) ∧ ResulttypeSub ts3' ts3 := sorry

/-- Rocq `subtyping.v:636` `instrtype_sub_compose_eq`. -/
theorem instrtype_sub_compose_eq (ts1 ts2 ts2' ts3 txs tys tzs : List valtype) :
    instrtype_sub (mkFunctype ts1 ts2) (mkFunctype txs tys) →
    instrtype_sub (mkFunctype ts2' ts3) (mkFunctype tys tzs) →
    ts2.length = ts2'.length →
    instrtype_sub (mkFunctype ts1 ts3) (mkFunctype txs tzs) ∧ ResulttypeSub ts2 ts2' := sorry

/-- Rocq `subtyping.v:646` `instrtype_sub_compose_le'`. -/
theorem instrtype_sub_compose_le' (ts1 ts2 ts3 ts4 txs tys tzs : List valtype) :
    instrtype_sub (mkFunctype ts1 ts2) (mkFunctype txs tys) →
    instrtype_sub (mkFunctype ts3 ts4) (mkFunctype tys tzs) →
    ts2.length ≤ ts3.length →
    instrtype_sub (mkFunctype ((ts3.take (ts3.length - ts2.length)) ++ ts1) ts4) (mkFunctype txs tzs) ∧
      ResulttypeSub ts2 (ts3.drop (ts3.length - ts2.length)) := sorry

/-- Rocq `subtyping.v:662` `instrtype_sub_compose_ge'`. -/
theorem instrtype_sub_compose_ge' (ts1 ts2 ts3 ts4 txs tys tzs : List valtype) :
    instrtype_sub (mkFunctype ts1 ts2) (mkFunctype txs tys) →
    instrtype_sub (mkFunctype ts3 ts4) (mkFunctype tys tzs) →
    ts3.length ≤ ts2.length →
    instrtype_sub (mkFunctype ts1 ((ts2.take (ts2.length - ts3.length)) ++ ts4)) (mkFunctype txs tzs) ∧
      ResulttypeSub (ts2.drop (ts2.length - ts3.length)) ts3 := sorry

/-- Rocq `subtyping.v:679` `instrtype_sub_compose1`. -/
theorem instrtype_sub_compose1 (ts1 ts2 ts3 ts4 txs tys tzs : List valtype) :
    instrtype_sub (mkFunctype ts1 ts2) (mkFunctype txs tys) →
    instrtype_sub (mkFunctype (ts3 ++ ts2) ts4) (mkFunctype tys tzs) →
    instrtype_sub (mkFunctype (ts3 ++ ts1) ts4) (mkFunctype txs tzs) := sorry

/-- Rocq `subtyping.v:688` `instrtype_sub_compose0`. Semantically identical to
    `instrtype_sub_compose` above (Rocq derives it via `compose1` instead, kept separate
    for call-site naming fidelity). -/
theorem instrtype_sub_compose0 (ts1 ts2 ts3 txs tys tzs : List valtype) :
    instrtype_sub (mkFunctype ts1 ts2) (mkFunctype txs tys) →
    instrtype_sub (mkFunctype ts2 ts3) (mkFunctype tys tzs) →
    instrtype_sub (mkFunctype ts1 ts3) (mkFunctype txs tzs) := sorry

/-- Rocq `subtyping.v:697` `instrtype_sub_compose2`. -/
theorem instrtype_sub_compose2 (ts1 ts2 ts3 ts4 txs tys tzs : List valtype) :
    instrtype_sub (mkFunctype ts1 (ts2 ++ ts3)) (mkFunctype txs tys) →
    instrtype_sub (mkFunctype ts3 ts4) (mkFunctype tys tzs) →
    instrtype_sub (mkFunctype ts1 (ts2 ++ ts4)) (mkFunctype txs tzs) := sorry

/-- Rocq `subtyping.v:706` `instrtype_sub_cancel_left`. -/
theorem instrtype_sub_cancel_left (t : valtype) (ts1 ts2 txs tys : List valtype) :
    instrtype_sub (mkFunctype (t :: ts1) (t :: ts2)) (mkFunctype txs tys) →
    instrtype_sub (mkFunctype ts1 ts2) (mkFunctype txs tys) := sorry

/-- Rocq `subtyping.v:720` `instrtype_sub_empty`. -/
theorem instrtype_sub_empty (txs tys : List valtype) :
    instrtype_sub (mkFunctype [] []) (mkFunctype txs tys) → ResulttypeSub txs tys := sorry

/-- Rocq `subtyping.v:732` `instrtype_sub_sub_empty`. -/
theorem instrtype_sub_sub_empty (txs tys : List valtype) :
    instrtype_sub (mkFunctype txs tys) (mkFunctype [] []) → txs = [] ∧ tys = [] := sorry

/-- Rocq `subtyping.v:747` `instrtype_sub_sub_empty1`. -/
theorem instrtype_sub_sub_empty1 (txs tys tzs : List valtype) :
    instrtype_sub (mkFunctype txs tys) (mkFunctype [] tzs) → txs = [] ∧ ResulttypeSub tys tzs := sorry

/-- Rocq `subtyping.v:761` `instrtype_sub_sub_empty2`. -/
theorem instrtype_sub_sub_empty2 (txs tys tzs : List valtype) :
    instrtype_sub (mkFunctype txs tys) (mkFunctype tzs []) → tys = [] ∧ ResulttypeSub tzs txs := sorry

/-- Rocq `subtyping.v:775` `instrtype_sub_iff_resulttype_sub`. -/
theorem instrtype_sub_iff_resulttype_sub (ts1 ts2 ts3 : List valtype) :
    ResulttypeSub ts1 ts2 ↔ instrtype_sub (mkFunctype ts3 ts1) (mkFunctype ts3 ts2) := sorry

/-- Rocq `subtyping.v:807` `instrtype_sub_iff_resulttype_sub'`. -/
theorem instrtype_sub_iff_resulttype_sub' (ts1 ts2 ts3 : List valtype) :
    ResulttypeSub ts1 ts2 ↔ instrtype_sub (mkFunctype ts2 ts3) (mkFunctype ts1 ts3) := sorry

/-- Rocq `subtyping.v:837` `instrtype_sub_extend`. -/
theorem instrtype_sub_extend (t1s t2s txs tys tzs : List valtype) :
    instrtype_sub (mkFunctype t1s t2s) (mkFunctype txs tys) →
    ∃ t3s, instrtype_sub (mkFunctype (t3s ++ t1s) tzs) (mkFunctype txs tzs) := sorry

/-- Rocq `subtyping.v:856` `instrtype_sub_add_same`. The explicit "frame rule" lemma. -/
theorem instrtype_sub_add_same (ts1 ts2 ts3 : List valtype) :
    instrtype_sub (mkFunctype ts1 ts2) (mkFunctype (ts3 ++ ts1) (ts3 ++ ts2)) := sorry

/-- Rocq `subtyping.v:867` `resulttype_sub_cons`. -/
theorem resulttype_sub_cons (t t' : valtype) (ts ts' : List valtype) :
    ResulttypeSub (t :: ts) (t' :: ts') → Valtype_sub t t' ∧ ResulttypeSub ts ts' := sorry

/-- Rocq `subtyping.v:878` `instr_subtyping_strengthen2`. Already proved (0 sorry) in a
    previous session's `typing_lemmas.lean` — see
    `claude-logging/for-claude/digest_prior_lean_attempts.md` §1A — worth porting that
    proof once definitions are confirmed aligned. -/
theorem instr_subtyping_strengthen2 (tx1 ty1 tx2 ty2 ts : List valtype) :
    instrtype_sub (mkFunctype tx1 ty1) (mkFunctype tx2 ty2) → ResulttypeSub ts tx2 →
    instrtype_sub (mkFunctype tx1 ty1) (mkFunctype ts ty2) := sorry

/-- Rocq `subtyping.v:898` (last declaration in file) `instr_subtyping_weaken2`. Already
    proved (0 sorry) in a previous session's `InstrtypeSub.lean` — see
    `claude-logging/for-claude/digest_prior_lean_attempts.md` §1D — this was one of the
    prior `typing_lemmas.lean`'s 4 open `sorry`s; worth porting that proof once definitions
    are confirmed aligned. -/
theorem instr_subtyping_weaken2 (tx1 ty1 tx2 ty2 ts : List valtype) :
    instrtype_sub (mkFunctype tx1 ty1) (mkFunctype tx2 ty2) → ResulttypeSub ty2 ts →
    instrtype_sub (mkFunctype tx1 ty1) (mkFunctype tx2 ts) := sorry

end TLC
