/-
  Rigorous tests for the `DecidableEq` instances that `wasm2.0.lean` generates
  via `derive_deceq` (see `ExtendedDeriveDecEq.lean`) for the 13 constructs
  that cannot use the standard `deriving DecidableEq`:

    instr, elemmode, datamode, func, global, elem, data, module,
    funcinst, store, state, admininstr, config

  Every type in this file that is not derive_deceq'd already gets a plain
  `deriving ... DecidableEq ...` from wasm2.0.lean itself, so this file only
  needs to stress the 13 above.

  Strategy per type:
    1. `example : DecidableEq T := inferInstance` — the instance exists and
       resolves through the standard typeclass mechanism (not just a bare def).
    2. `checkDistinctSamples` — for a hand-picked list of samples that are
       *known by construction* to be pairwise distinct, assert
       `decide (a = a) = true` for every sample (reflexivity, no crashes) and
       `decide (a ≠ b) = true` for every off-diagonal pair (ground-truth
       distinctness — independent of any other derivation).
    3. `checkAgreesWithBEq` — for the same samples, assert that the
       independently-derived (standard Lean) `BEq` instance agrees with the
       `ExtendedDeriveDecEq`-derived `DecidableEq` instance on every pair.
       Because the two are generated by completely different code paths, a
       systematic disagreement is strong evidence of a bug in one of them.
    4. A few explicit "same value, built two different ways" checks, to
       confirm equality isn't accidentally testing literal term identity.

  All `#guard`s are checked by Lean's evaluator when this file is elaborated;
  if any one of them is false, elaboration fails and the build breaks loudly.
-/
import «wasm2.0»

namespace TempTestDecEq

/-- Every sample is reflexively equal to itself, and distinct from every
    other sample in the list (ground truth, since samples are hand-picked to
    differ). -/
def checkDistinctSamples {α : Type} [DecidableEq α] [Inhabited α] (xs : List α) : Bool :=
  let idxs := List.range xs.length
  idxs.all (fun i => idxs.all (fun j =>
    if i == j then decide (xs[i]! = xs[j]!)
    else decide (xs[i]! ≠ xs[j]!)))

/-- The derive_deceq-derived `DecidableEq` agrees with the independently
    auto-derived `BEq` on every pair of samples. -/
def checkAgreesWithBEq {α : Type} [DecidableEq α] [BEq α] [Inhabited α] (xs : List α) : Bool :=
  xs.all (fun a => xs.all (fun b => (a == b) == decide (a = b)))

-- ── small building blocks ───────────────────────────────────────────────

def u (k : Nat) : uN := uN.mk_uN k
def byt (k : Nat) : byte := byte.mk_byte k
def ch (k : Nat) : char := char.mk_char k
def nm (ks : List Nat) : name := name.mk_name (ks.map ch)

def bt0 : blocktype := blocktype._RESULT none
def bt1 : blocktype := blocktype._IDX (u 3)

-- ══════════════════════════════════════════════════════════════════════
-- instr
-- ══════════════════════════════════════════════════════════════════════

def i1 : instr := instr.NOP
def i2 : instr := instr.DROP
def i3 : instr := instr.UNREACHABLE
def i4 : instr := instr.RETURN
def i5 : instr := instr.REF_IS_NULL
def i6 : instr := instr.MEMORY_SIZE
def i7 : instr := instr.MEMORY_GROW
def i8 : instr := instr.BR (u 1)
def i9 : instr := instr.BR (u 2)
def i10 : instr := instr.BR_IF (u 1)                          -- same field as i8, different ctor
def i11 : instr := instr.CALL (u 5)
def i12 : instr := instr.CALL_INDIRECT (u 1) (u 2)
def i13 : instr := instr.CALL_INDIRECT (u 2) (u 1)             -- swapped args
def i14 : instr := instr.SELECT none
def i15 : instr := instr.SELECT (some [valtype.I32])
def i16 : instr := instr.SELECT (some [valtype.I32, valtype.I64])
def i17 : instr := instr.SELECT (some [valtype.I64, valtype.I32])  -- order matters
def i18 : instr := instr.CONST numtype.I32 (num_.mk_num__0 Inn.I32 (u 42))
def i19 : instr := instr.CONST numtype.I32 (num_.mk_num__0 Inn.I32 (u 43))  -- diff payload
def i20 : instr := instr.CONST numtype.I64 (num_.mk_num__0 Inn.I64 (u 42))  -- diff numtype/Inn
def i21 : instr := instr.EXTEND numtype.I32 8
def i22 : instr := instr.EXTEND numtype.I32 16
def i23 : instr := instr.REF_NULL reftype.FUNCREF
def i24 : instr := instr.REF_NULL reftype.EXTERNREF
def i25 : instr := instr.LOCAL_GET (u 3)
def i26 : instr := instr.LOCAL_SET (u 3)                       -- same idx, diff ctor
def i27 : instr := instr.GLOBAL_GET (u 3)
def i28 : instr := instr.TABLE_COPY (u 1) (u 2)
def i29 : instr := instr.TABLE_COPY (u 2) (u 1)
def i30 : instr := instr.BR_TABLE [u 1, u 2, u 3] (u 4)
def i31 : instr := instr.BR_TABLE [u 1, u 2] (u 4)              -- shorter list
def i32 : instr := instr.BR_TABLE [u 1, u 2, u 99] (u 4)        -- same length, last elem differs
def i33 : instr := instr.LOAD numtype.I32 none (memarg.MKmemarg (u 0) (u 0))
def i34 : instr := instr.LOAD numtype.I32 none (memarg.MKmemarg (u 0) (u 1))
def i35 : instr :=
  instr.LOAD numtype.I32 (some (loadop_.mk_loadop__0 Inn.I32 (loadop_Inn.mk_loadop_Inn (sz.mk_sz 8) sx.U)))
    (memarg.MKmemarg (u 0) (u 0))
def i36 : instr := instr.STORE numtype.I32 none (memarg.MKmemarg (u 0) (u 0))
def i37 : instr := instr.STORE numtype.I32 (some (sz.mk_sz 16)) (memarg.MKmemarg (u 0) (u 0))
def i38 : instr := instr.MEMORY_INIT (u 7)
def i39 : instr := instr.DATA_DROP (u 7)                       -- same idx, diff ctor as i38
def i40 : instr := instr.BLOCK bt0 [i1, i2]
def i41 : instr := instr.BLOCK bt0 [i1, i3]                    -- diff 2nd elem
def i42 : instr := instr.BLOCK bt0 [i1, i2, i3]                -- diff length
def i43 : instr := instr.BLOCK bt1 [i1, i2]                    -- diff blocktype
def i44 : instr := instr.LOOP bt0 [i1, i2]                     -- same fields as i40, diff ctor
def i45 : instr := instr.IFELSE bt0 [i1] [i2]
def i46 : instr := instr.IFELSE bt0 [i1] [i3]                  -- diff else-branch
def i47 : instr := instr.IFELSE bt0 [i2] [i2]                  -- diff then-branch
def i48 : instr := instr.BLOCK bt0 [i40, i44, i45]              -- depth-2 nesting
def i49 : instr := instr.BLOCK bt0 [instr.BLOCK bt0 [instr.BLOCK bt0 [i1]]]  -- depth-3 self-nesting

def instrSamples : List instr :=
  [i1, i2, i3, i4, i5, i6, i7, i8, i9, i10, i11, i12, i13, i14, i15, i16, i17,
   i18, i19, i20, i21, i22, i23, i24, i25, i26, i27, i28, i29, i30, i31, i32,
   i33, i34, i35, i36, i37, i38, i39, i40, i41, i42, i43, i44, i45, i46, i47,
   i48, i49]

example : DecidableEq instr := inferInstance
#guard checkDistinctSamples instrSamples
#guard checkAgreesWithBEq instrSamples

-- same value, built a different way (List.append instead of a literal)
def i40b : instr := instr.BLOCK bt0 ([i1] ++ [i2])
#guard i40b = i40
#guard i8 ≠ i10   -- illustrative: cross-constructor, same payload

-- ══════════════════════════════════════════════════════════════════════
-- elemmode
-- ══════════════════════════════════════════════════════════════════════

def em1 : elemmode := elemmode.PASSIVE
def em2 : elemmode := elemmode.DECLARE
def em3 : elemmode := elemmode.ACTIVE (u 0) [i1, i2]
def em4 : elemmode := elemmode.ACTIVE (u 1) [i1, i2]  -- diff tableidx
def em5 : elemmode := elemmode.ACTIVE (u 0) [i1, i3]  -- diff expr
def em6 : elemmode := elemmode.ACTIVE (u 0) []        -- empty expr

def elemmodeSamples : List elemmode := [em1, em2, em3, em4, em5, em6]

example : DecidableEq elemmode := inferInstance
#guard checkDistinctSamples elemmodeSamples
#guard checkAgreesWithBEq elemmodeSamples

-- ══════════════════════════════════════════════════════════════════════
-- datamode
-- ══════════════════════════════════════════════════════════════════════

def dm1 : datamode := datamode.PASSIVE
def dm2 : datamode := datamode.ACTIVE (u 0) [i1, i2]
def dm3 : datamode := datamode.ACTIVE (u 1) [i1, i2]
def dm4 : datamode := datamode.ACTIVE (u 0) [i1, i3]

def datamodeSamples : List datamode := [dm1, dm2, dm3, dm4]

example : DecidableEq datamode := inferInstance
#guard checkDistinctSamples datamodeSamples
#guard checkAgreesWithBEq datamodeSamples

-- ══════════════════════════════════════════════════════════════════════
-- func
-- ══════════════════════════════════════════════════════════════════════

def lc1 : «local» := «local».LOCAL valtype.I32
def lc2 : «local» := «local».LOCAL valtype.I64

def f1 : func := func.FUNC (u 0) [lc1, lc2] [i1, i2]
def f2 : func := func.FUNC (u 1) [lc1, lc2] [i1, i2]  -- diff typeidx
def f3 : func := func.FUNC (u 0) [lc2, lc1] [i1, i2]  -- diff local order
def f4 : func := func.FUNC (u 0) [lc1, lc2] [i1, i3]  -- diff body
def f5 : func := func.FUNC (u 0) [] []                -- empty everything

def funcSamples : List func := [f1, f2, f3, f4, f5]

example : DecidableEq func := inferInstance
#guard checkDistinctSamples funcSamples
#guard checkAgreesWithBEq funcSamples

-- ══════════════════════════════════════════════════════════════════════
-- global
-- ══════════════════════════════════════════════════════════════════════

def gt1 : globaltype := globaltype.mk_globaltype none valtype.I32
def gt2 : globaltype := globaltype.mk_globaltype (some r_MUT.MUT) valtype.I32

def g1 : global := global.GLOBAL gt1 [i1]
def g2 : global := global.GLOBAL gt2 [i1]  -- diff globaltype
def g3 : global := global.GLOBAL gt1 [i2]  -- diff expr

def globalSamples : List global := [g1, g2, g3]

example : DecidableEq global := inferInstance
#guard checkDistinctSamples globalSamples
#guard checkAgreesWithBEq globalSamples

-- ══════════════════════════════════════════════════════════════════════
-- elem
-- ══════════════════════════════════════════════════════════════════════

def e1 : elem := elem.ELEM reftype.FUNCREF [[i1], [i2]] em3
def e2 : elem := elem.ELEM reftype.EXTERNREF [[i1], [i2]] em3  -- diff reftype
def e3 : elem := elem.ELEM reftype.FUNCREF [[i1], [i3]] em3    -- diff nested elem
def e4 : elem := elem.ELEM reftype.FUNCREF [[i1], [i2]] em4    -- diff elemmode
def e5 : elem := elem.ELEM reftype.FUNCREF [[i1, i2]] em3      -- diff list-of-list shape

def elemSamples : List elem := [e1, e2, e3, e4, e5]

example : DecidableEq elem := inferInstance
#guard checkDistinctSamples elemSamples
#guard checkAgreesWithBEq elemSamples

def e1b : elem := elem.ELEM reftype.FUNCREF ([[i1]] ++ [[i2]]) em3
#guard e1b = e1

-- ══════════════════════════════════════════════════════════════════════
-- data
-- ══════════════════════════════════════════════════════════════════════

def d1 : data := data.DATA [byt 1, byt 2] dm2
def d2 : data := data.DATA [byt 1, byt 3] dm2  -- diff bytes
def d3 : data := data.DATA [byt 1, byt 2] dm3  -- diff datamode

def dataSamples : List data := [d1, d2, d3]

example : DecidableEq data := inferInstance
#guard checkDistinctSamples dataSamples
#guard checkAgreesWithBEq dataSamples

-- ══════════════════════════════════════════════════════════════════════
-- module
-- ══════════════════════════════════════════════════════════════════════

def emptyFunctype : functype := functype.mk_functype (list.mk_list []) (list.mk_list [])

def ty1 : type := type.TYPE emptyFunctype
def im1 : «import» := «import».IMPORT (nm [1,2]) (nm [3,4]) (externtype.FUNC emptyFunctype)
def tbl1 : table := table.TABLE (tabletype.mk_tabletype (limits.mk_limits (u 1) none) reftype.FUNCREF)
def memv1 : mem := mem.MEMORY (memtype.PAGE (limits.mk_limits (u 1) (some (u 2))))
def exp1 : «export» := «export».EXPORT (nm [5,6]) (externidx.FUNC (u 0))
def strt1 : start := start.START (u 0)

def m1 : module := module.MODULE [ty1] [im1] [f1] [g1] [tbl1] [memv1] [e1] [d1] (some strt1) [exp1]
def m2 : module := module.MODULE [] [im1] [f1] [g1] [tbl1] [memv1] [e1] [d1] (some strt1) [exp1]       -- diff types (empty)
def m3 : module := module.MODULE [ty1] [im1] [f2] [g1] [tbl1] [memv1] [e1] [d1] (some strt1) [exp1]    -- diff funcs
def m4 : module := module.MODULE [ty1] [im1] [f1] [g1] [tbl1] [memv1] [e2] [d1] (some strt1) [exp1]    -- diff elems
def m5 : module := module.MODULE [ty1] [im1] [f1] [g1] [tbl1] [memv1] [e1] [d1] none [exp1]            -- no start
def m6 : module := module.MODULE [ty1] [im1] [f1] [g1] [tbl1] [memv1] [e1] [d1] (some strt1) []        -- no exports
def m7 : module := module.MODULE [] [] [] [] [] [] [] [] none []                                       -- fully empty

def moduleSamples : List module := [m1, m2, m3, m4, m5, m6, m7]

example : DecidableEq module := inferInstance
#guard checkDistinctSamples moduleSamples
#guard checkAgreesWithBEq moduleSamples

def m1b : module :=
  module.MODULE [ty1] [im1] (List.reverse (List.reverse [f1])) [g1] [tbl1] [memv1] [e1] [d1] (some strt1) [exp1]
#guard m1b = m1

-- ══════════════════════════════════════════════════════════════════════
-- funcinst
-- ══════════════════════════════════════════════════════════════════════

def mi1 : moduleinst := moduleinst.MKmoduleinst [] [] [] [] [] [] [] []
def mi2 : moduleinst := moduleinst.MKmoduleinst [emptyFunctype] [] [] [] [] [] [] []  -- diff TYPES
def exin1 : exportinst := exportinst.MKexportinst (nm [7,8]) (externaddr.FUNC 0)
def mi3 : moduleinst := moduleinst.MKmoduleinst [] [] [] [] [] [] [] [exin1]          -- diff EXPORTS

def fi1 : funcinst := funcinst.MKfuncinst emptyFunctype mi1 f1
def fi2 : funcinst := funcinst.MKfuncinst emptyFunctype mi2 f1  -- diff MODULE
def fi3 : funcinst := funcinst.MKfuncinst emptyFunctype mi1 f2  -- diff CODE
def fi4 : funcinst :=
  funcinst.MKfuncinst (functype.mk_functype (list.mk_list [valtype.I32]) (list.mk_list [])) mi1 f1  -- diff TYPE

def funcinstSamples : List funcinst := [fi1, fi2, fi3, fi4]

example : DecidableEq funcinst := inferInstance
#guard checkDistinctSamples funcinstSamples
#guard checkAgreesWithBEq funcinstSamples

-- ══════════════════════════════════════════════════════════════════════
-- store
-- ══════════════════════════════════════════════════════════════════════

def glin1 : globalinst := globalinst.MKglobalinst gt1 (val.CONST numtype.I32 (num_.mk_num__0 Inn.I32 (u 0)))
def tbin1 : tableinst :=
  tableinst.MKtableinst (tabletype.mk_tabletype (limits.mk_limits (u 1) none) reftype.FUNCREF)
    [ref.REF_NULL reftype.FUNCREF]
def meminst1 : meminst := meminst.MKmeminst (memtype.PAGE (limits.mk_limits (u 1) none)) [byt 0, byt 0]
def elin1 : eleminst := eleminst.MKeleminst reftype.FUNCREF [ref.REF_NULL reftype.FUNCREF]
def dain1 : datainst := datainst.MKdatainst [byt 1]

def s1 : store := store.MKstore [fi1] [glin1] [tbin1] [meminst1] [elin1] [dain1]
def s2 : store := store.MKstore [fi2] [glin1] [tbin1] [meminst1] [elin1] [dain1]  -- diff FUNCS
def s3 : store := store.MKstore [fi1] [glin1] [tbin1] [meminst1] [elin1] []       -- diff DATAS

def storeSamples : List store := [s1, s2, s3]

example : DecidableEq store := inferInstance
#guard checkDistinctSamples storeSamples
#guard checkAgreesWithBEq storeSamples

-- ══════════════════════════════════════════════════════════════════════
-- state
-- ══════════════════════════════════════════════════════════════════════

def fr1 : frame := frame.MKframe [val.CONST numtype.I32 (num_.mk_num__0 Inn.I32 (u 1))] mi1
def fr2 : frame := frame.MKframe [val.CONST numtype.I32 (num_.mk_num__0 Inn.I32 (u 2))] mi1  -- diff LOCALS

def sta : state := state.mk_state s1 fr1
def stb : state := state.mk_state s1 fr2  -- diff frame
def stc : state := state.mk_state s2 fr1  -- diff store

def stateSamples : List state := [sta, stb, stc]

example : DecidableEq state := inferInstance
#guard checkDistinctSamples stateSamples
#guard checkAgreesWithBEq stateSamples

-- ══════════════════════════════════════════════════════════════════════
-- admininstr (self-recursive via `List admininstr`, plus `List instr`)
-- ══════════════════════════════════════════════════════════════════════

def ai1 : admininstr := admininstr.NOP
def ai2 : admininstr := admininstr.TRAP
def ai3 : admininstr := admininstr.BR (u 1)
def ai4 : admininstr := admininstr.REF_FUNC_ADDR 5
def ai5 : admininstr := admininstr.REF_HOST_ADDR 5   -- same payload, diff ctor from ai4
def ai6 : admininstr := admininstr.CALL_ADDR 5        -- same payload, diff ctor again
def ai7 : admininstr := admininstr.LABEL_ 0 [i1, i2] [ai1, ai2]
def ai8 : admininstr := admininstr.LABEL_ 0 [i1, i2] [ai1, ai3]   -- diff admininstr_lst
def ai9 : admininstr := admininstr.LABEL_ 0 [i1, i3] [ai1, ai2]   -- diff instr_lst
def ai10 : admininstr := admininstr.LABEL_ 1 [i1, i2] [ai1, ai2]  -- diff n
def ai11 : admininstr := admininstr.FRAME_ 0 fr1 [ai1, ai2]
def ai12 : admininstr := admininstr.FRAME_ 0 fr2 [ai1, ai2]       -- diff frame
def ai13 : admininstr := admininstr.FRAME_ 0 fr1 [ai1, ai3]       -- diff admininstr_lst
def ai14 : admininstr := admininstr.BLOCK bt0 [i1, i2]            -- List instr field, non-recursive ctor
def ai15 : admininstr :=                                          -- depth-3 nested mutual recursion
  admininstr.LABEL_ 0 [] [ai11, admininstr.LABEL_ 1 [i1] [ai2, ai3]]
def ai16 : admininstr :=                                          -- same shape as ai15 but differs deep inside
  admininstr.LABEL_ 0 [] [ai11, admininstr.LABEL_ 1 [i1] [ai2, ai1]]

def admininstrSamples : List admininstr :=
  [ai1, ai2, ai3, ai4, ai5, ai6, ai7, ai8, ai9, ai10, ai11, ai12, ai13, ai14, ai15, ai16]

example : DecidableEq admininstr := inferInstance
#guard checkDistinctSamples admininstrSamples
#guard checkAgreesWithBEq admininstrSamples

def ai7b : admininstr := admininstr.LABEL_ (0 + 0) ([i1] ++ [i2]) ([ai1] ++ [ai2])
#guard ai7b = ai7

-- ══════════════════════════════════════════════════════════════════════
-- config
-- ══════════════════════════════════════════════════════════════════════

def cfg1 : config := config.mk_config sta [ai1, ai7]
def cfg2 : config := config.mk_config sta [ai1, ai8]  -- diff admininstr list
def cfg3 : config := config.mk_config stb [ai1, ai7]  -- diff state

def configSamples : List config := [cfg1, cfg2, cfg3]

example : DecidableEq config := inferInstance
#guard checkDistinctSamples configSamples
#guard checkAgreesWithBEq configSamples

-- ══════════════════════════════════════════════════════════════════════
#eval IO.println "All derive_deceq DecidableEq tests in test_deceq.lean passed."

end TempTestDecEq
