open Interpreter_ocaml.Dl_codegen_types
open Interpreter_ocaml.Dl_codegen
open Interpreter_ocaml.Dl_codegen_util
(*open Interpreter_ocaml.Construct_ocaml*)
open Interpreter_ocaml.Construct_ocaml_new
open Reference_interpreter.Script
open Reference_interpreter.Source
open Reference_interpreter.Value
open Reference_interpreter.Run
open Reference_interpreter.Types

module Register = Backend_interpreter.Ds.Register(struct type t = moduleinst end)
(*module Modules = Backend_interpreter.Ds.Register(struct type t = module_ end)*)
module Modules = Backend_interpreter.Ds.Modules

module RI = Reference_interpreter
module I = Backend_interpreter

let verbose = ref false
let invalids = ref 0

(* the initial ocaml store and spectest before any runner file. 
Calling once because `ocaml_of_moduleinst` is slow. *)
let ocaml_store = ocaml_of_store (Backend_animation.State_v.Store.get ())
let ocaml_spectest = ocaml_of_moduleinst (Backend_animation.Runner.spectest_v)

(* TEMP DEBUGGING *)
(*let string_of_uc_un = function
  | C_pct__uc_un n -> "C_pct__uc_un (" ^ (string_of_int n) ^ ")"
let string_of_num_ = function
  | Mk_num__0_num_ (_, n) -> "Mk_num__0_num_ (" ^ (string_of_uc_un n) ^ ")"
  | Mk_num__1_num_ _ -> "float num_"
let string_of_dlinstr = function
  | NOP_instr -> "NOP_instr"
  | UNREACHABLE_instr -> "UNREACHABLE_instr"
  | DROP_instr -> "DROP_instr"
  | SELECT_instr _ -> "SELECT_instr"
  | CALL_instr _ -> "CALL_instr"
  | CALL_REF_instr _ -> "CALL_REF_instr"
  | RETURN_instr -> "RETURN_instr"
  | RETURN_CALL_REF_instr _ -> "RETURN_CALL_REF_instr"
  | THROW_REF_instr -> "THROW_REF_instr"
  | CONST_instr (nt, n) -> "CONST_instr " ^ (match nt with I32_numtype -> "I32" | _ -> "other") ^ " " ^ (string_of_num_ n)
  | BINOP_instr _ -> "BINOP_instr"
  | REF_dot_NULL_instr _ -> "REF_dot_NULL_instr"
  | LOCAL_dot_GET_instr _ -> "LOCAL_dot_GET_instr"
  | TABLE_dot_INIT_instr _ -> "TABLE_dot_INIT_instr"
  | ELEM_dot_DROP_instr _ -> "ELEM_dot_DROP_instr"
  | MEMORY_dot_INIT_instr _ -> "MEMORY_dot_INIT_instr"
  | DATA_dot_DROP_instr _ -> "DATA_dot_DROP_instr"
  | REF_dot_I31_NUM_instr _ -> "REF_dot_I31_NUM_instr"
  | REF_dot_STRUCT_ADDR_instr _ -> "REF_dot_STRUCT_ADDR_instr"
  | REF_dot_ARRAY_ADDR_instr _ -> "REF_dot_ARRAY_ADDR_instr"
  | REF_dot_FUNC_ADDR_instr _ -> "REF_dot_FUNC_ADDR_instr"
  | REF_dot_EXN_ADDR_instr _ -> "REF_dot_EXN_ADDR_instr"
  | REF_dot_HOST_ADDR_instr _ -> "REF_dot_HOST_ADDR_instr"
  | REF_dot_EXTERN_instr _ -> "REF_dot_EXTERN_instr"
  | TRAP_instr -> "TRAP_instr"
  | BR_instr _ -> "BR_instr"
  | LABEL__pct__lbrackcu_pct__rbrackcu_pct__instr _ -> "LABEL"
  | FRAME__pct__lbrackcu_pct__rbrackcu_pct__instr _ -> "FRAME"
  | MEMORY_dot_COPY_instr _ -> "MEMORY_dot_COPY_instr"
  | MEMORY_dot_FILL_instr _ -> "MEMORY_dot_FILL_instr"
  | MEMORY_dot_GROW_instr _ -> "MEMORY_dot_GROW_instr"
  | MEMORY_dot_SIZE_instr _ -> "MEMORY_dot_SIZE_instr"
  | TABLE_dot_COPY_instr _ -> "TABLE_dot_COPY_instr"
  | TABLE_dot_GROW_instr _ -> "TABLE_dot_GROW_instr"
  | TABLE_dot_SIZE_instr _ -> "TABLE_dot_SIZE_instr"*)
(* ============ *)

let print_runner_result name result =
  let (num_success, total), execution_time = result in
  let percentage =
    if total = 0 then 100.
    else (float_of_int num_success /. float_of_int total) *. 100.
  in

  let emoji =
    if percentage = 100. then ":D :D"
    else if percentage >= 90. then ":)"
    else ":("
  in

  if name = "Total" then
    Printf.printf "Total [%d/%d] (%.2f%%) %s\n\n"
      num_success total percentage emoji
  else
    Printf.printf "- %d/%d (%.2f%%) %s\n\n"
      num_success total percentage emoji;

  Printf.printf "%s took %.5f s.\n%!" name execution_time;
  flush stdout

let globalstore = ref {
  uc_tags_store = [];
  uc_globals_store = [];
  uc_mems_store = [];
  uc_tables_store = [];
  uc_funcs_store = [];
  uc_datas_store = [];
  uc_elems_store = [];
  uc_structs_store = [];
  uc_arrays_store = [];
  uc_exns_store = [];
  uc_host_store = HOSTSTATE_hoststate
}

(* this should be generated by the ocaml gen but it is not since the hoststate is not composable oops *)
let update_store s2 = { !globalstore with
  uc_tags_store = !globalstore.uc_tags_store @ s2.uc_tags_store;
  uc_globals_store = !globalstore.uc_globals_store @ s2.uc_globals_store;
  uc_mems_store = !globalstore.uc_mems_store @ s2.uc_mems_store;
  uc_tables_store = !globalstore.uc_tables_store @ s2.uc_tables_store;
  uc_funcs_store = !globalstore.uc_funcs_store @ s2.uc_funcs_store;
  uc_datas_store = !globalstore.uc_datas_store @ s2.uc_datas_store;
  uc_elems_store = !globalstore.uc_elems_store @ s2.uc_elems_store;
  uc_structs_store = !globalstore.uc_structs_store @ s2.uc_structs_store;
  uc_arrays_store = !globalstore.uc_arrays_store @ s2.uc_arrays_store;
  uc_exns_store = !globalstore.uc_exns_store @ s2.uc_exns_store
}

(* The idea is to go from OCaml -> VL -> RI, since OCaml -> VL is automatic. But, if the value is a reference, then the VL -> RI function will not work since it looks into the VL store, which is not used by the OCaml interpreter. Thus, the OCaml -> RI encoding for refs is manually written. *)

let rec ri_ref_of_ocaml (r : ref) = match r with
    | REF_dot_I31_NUM_ref (C_pct__uc_un n) -> (RI.I31.I31Ref (Z.to_int n))
    | REF_dot_NULL_ADDR_ref                -> NullRef
    | REF_dot_STRUCT_ADDR_ref _
    | REF_dot_ARRAY_ADDR_ref _
    | REF_dot_FUNC_ADDR_ref _ -> 
      Backend_animation.State_v.Store.put (vl_of_store !globalstore);
      Backend_animation.Construct_v_new.vl_to_ref (vl_of_ref r)
    | REF_dot_HOST_ADDR_ref n              -> RI.Script.HostRef (Z.to_int32 n)
    | REF_dot_EXTERN_ref ref_              -> RI.Extern.ExternRef (ri_ref_of_ocaml ref_)

let ri_of_ocaml (i : instr) = match i with
  | REF_dot_I31_NUM_instr _ 
  | REF_dot_NULL_ADDR_instr
  | REF_dot_STRUCT_ADDR_instr _
  | REF_dot_ARRAY_ADDR_instr _
  | REF_dot_FUNC_ADDR_instr _
  | REF_dot_HOST_ADDR_instr _
  | REF_dot_EXTERN_instr _ ->  RI.Value.Ref (ri_ref_of_ocaml (ref_of_instr i))
  | _ -> i |> vl_of_instr |> Backend_animation.Construct_v_new.vl_to_value

let success = 1,1
let pass = 0, 0
let fail = 0, 1 
let print_fail at failtype expected actual =
  print_endline (RI.Source.string_of_region at ^ ": Expected " ^ failtype ^ " failure: " ^ expected ^ ":(");
  print_endline ("Got " ^ actual ^ ":O");
  fail
let string_of_values = Backend_animation.Value.string_of_values

let int_of_ocamlchar (char : DL.char) = match char with
  | DL.C_pct__char n -> Z.to_int n
let string_of_ocamlname = function
  | DL.C_pct__name chars ->
      chars |> List.map int_of_ocamlchar |> Util.Utf8.encode

(* --- copied from manual construct_ocaml for now --- *)
(*let ocaml_of_value (v : value) : val_ =
  match v with
  | Num (I32 n) -> DL.CONST_val_ (DL.I32_numtype, DL.C_pct_num_ (Int32.to_int n))
  | _ -> failwith "TODO: implement non-I32 values"*)

(*let ocaml_of_literal (lit : literal) : val_ =
  ocaml_of_value lit.it*)

let heaptype_of_ocaml = function
  | DL.ANY_heaptype -> AnyHT
  | DL.EQ_heaptype -> EqHT
  | DL.I31_heaptype -> I31HT
  | DL.STRUCT_heaptype -> StructHT
  | DL.ARRAY_heaptype -> ArrayHT
  | DL.NONE_heaptype -> NoneHT
  | DL.FUNC_heaptype -> FuncHT
  | DL.NOFUNC_heaptype -> NoFuncHT
  | DL.EXN_heaptype -> ExnHT
  | DL.NOEXN_heaptype -> NoExnHT
  | DL.EXTERN_heaptype -> ExternHT
  | DL.NOEXTERN_heaptype -> NoExternHT
  | DL.BOT_heaptype -> BotHT
  | DL.C_IDX_heaptype _ -> failwith "TODO: implement C_IDX_heaptype"
  | DL.REC_heaptype _ -> failwith "TODO: implement REC_heaptype"
  | DL.C_DEF_heaptype _ -> failwith "TODO: implement C_DEF_heaptype"

(*let val_of_ocaml (instr: DL.instr) : value =
  match instr with
  | DL.CONST_instr (nt, num) -> 
    let C_pct__uc_un n = num in 
    begin match nt with 
    | DL.I32_numtype -> Num (I32 (Int32.of_int n))
    | _              -> failwith "TODO: non-I32 const"
    end
  | DL.REF_dot_NULL_instr ht  -> Ref (NullRef (heaptype_of_ocaml ht))
  | _ -> failwith (Printf.sprintf "TODO: not const or null ref instr/val: %s" (string_of_dlinstr instr))*)

(* -------- *)

let get_export name moduleinst_name =
  let exports = (Register.find moduleinst_name).uc_exports_moduleinst in 
  List.find (fun export -> (string_of_ocamlname export.uc_name_exportinst) = name) exports

let get_export_addr name moduleinst_name =
  let export_addr = get_export name moduleinst_name in
  (*Printf.printf "Getting funcaddr %s from moduleinst %s...\n" name moduleinst_name;*)
  match export_addr.uc_addr_exportinst with
  | DL.FUNC_externaddr funcaddr -> funcaddr
  | _ -> failwith ("Export " ^ name ^ " is not a function.")

let externaddr_from_import import = 
  let IMPORT_import (moduleinst_name, item_name, _) = import in 
  let export = get_export (string_of_ocamlname item_name) (string_of_ocamlname moduleinst_name) in 
  export.uc_addr_exportinst

(* todo change this to not use uncase *)
let get_moduleinst config =
  let C_pct__semi_pct__config (state, instrs) = config in
  let C_pct__semi_pct__state (store', frame') = state in
  globalstore := store';
  frame'.uc_module_frame, instrs

let instantiate_helper (m : module_) = 
  let t1 = Sys.time () in
  (if !verbose then
  Printf.printf "[Instantiating module...]\n");  
  let MODULE_module_ (_, imports, _, _, _, _, _, _, _, _, _) = m in
  let externaddrs = List.map externaddr_from_import imports in
  let config' = instantiate_fn !globalstore m externaddrs in
  let C_pct__semi_pct__config (_, instrs) = config' in
  let config'' = steps_fn config' (Z.of_int 256) in
  let t2 = Sys.time () in
  (if !verbose then
  Printf.printf "instantiate took %f s :)\n" (t2 -. t1));
  get_moduleinst config''

let invoke_helper module_ funcname args =
  let t1 = Sys.time () in
  (if !verbose then
  Printf.printf "[Invoking %s...]\n" funcname);
  let funcaddr = get_export_addr funcname module_ in
  let val_args = List.map (fun lit -> lit.it) args in
  (*let il_args = List.map Backend_animation.Construct.il_of_value val_args in
  let args' = List.map ocaml_of_val_ il_args in*)
  let vl_args = List.map Backend_animation.Construct_v_new.vl_of_value val_args in
  let args' = List.map ocaml_of_val_ vl_args in
  let result = invoke_fn !globalstore funcaddr args' in
  let result' = steps_fn result (Z.of_int 256) in
  let C_pct__semi_pct__config (state', _) = result' in
  let C_pct__semi_pct__state (store', _) = state' in
  globalstore := store';
  let t2 = Sys.time () in
  (if !verbose then
  Printf.printf "invoke %s took %f s :D\n" funcname (t2 -. t1));
  result'

let run_action action =
  match action.it with
  | Invoke (var_opt, funcname, args) ->
    invoke_helper (Register.get_module_name var_opt) (Util.Utf8.encode funcname) args
  | _ -> failwith "TODO: implement other actions"

let test_assertion assertion =
  match assertion.it with
  | AssertReturn (action, expected) ->
    let C_pct__semi_pct__config (_, vals) = run_action action in 
    (*let result_il = List.map il_of_instr vals in
    let result = List.map  Backend_animation.Construct.il_to_value result_il in*)
    (*let result_vl = List.map vl_of_val_new vals in
    let result = List.map Backend_animation.Construct_v_new.vl_to_value result_vl in*)
    let result = List.map ri_of_ocaml vals in
    assert_results no_region result expected;
    success
  | AssertTrap (action, re) ->
    let C_pct__semi_pct__config (_, vals) = run_action action in
    let result_vl = List.map vl_of_instr vals in
    (match result_vl with
    | [ CaseV ([["TRAP"]], []) ] -> success
    | _ -> print_fail assertion.at "runtime" re (string_of_values ", " result_vl)
    )
  | AssertException action ->
    let C_pct__semi_pct__config (_, vals) = run_action action in
    let result_vl = List.map vl_of_instr vals in
    (match result_vl with
    | [ CaseV ([["REF.EXN_ADDR"];[]], _); CaseV ([["THROW_REF"]], []) ] -> success
    | _ -> print_fail assertion.at "expected exception" "" (string_of_values ", " result_vl)
    )
  | AssertUninstantiable (var_opt, re) ->
    let (moduleinst, instrs) = Modules.find (Modules.get_module_name var_opt) 
    |> Backend_animation.Construct_v_new.vl_of_module
    |> ocaml_of_module_
    |> instantiate_helper in
    let result_vl = List.map vl_of_instr instrs in
    (match result_vl with
    | [ CaseV ([["TRAP"]], []) ]
    | [ CaseV ([["REF.EXN_ADDR"];[]], _); CaseV ([["THROW_REF"]], []) ] -> success
    | _ -> print_fail assertion.at "instantiation" re (string_of_values ", " result_vl)
    )
  | AssertInvalid (def, re)
  | AssertInvalidCustom (def, re) ->
    (*(match def |> Backend_animation.Runner.module_of_def |> fun ri_m ->
    Fun.const ri_m (Reference_interpreter.Valid.check_module ri_m) 
    |> Backend_animation.Construct_v_new.vl_of_module
    |> ocaml_of_module_
    |> instantiate_helper |> ignore with
    | exception RI.Valid.Invalid _ -> success
    | exception I.Exception.Invalid _ -> success
    | _ -> print_fail assertion.at "validation" re "module instance") *)
    invalids := !invalids + 1;
    pass
  | AssertExhaustion (action, re) ->
    (match run_action action with
    | exception I.Exception.OutOfMemory -> success
    | vs -> print_fail assertion.at "runtime" re ""
    )
  | _ -> pass

let run_command oc cmd = 
  let start_time = Sys.time () in
  try 
  (let res = begin match cmd.it with
  | Module (var_opt, def) ->
    (if !verbose then
    Printf.printf "[Defining module %s...]\n" (Option.fold ~none:"[_]" ~some:(fun var -> var.it) var_opt));
    def
    |> Backend_animation.Runner.module_of_def
    |> Modules.add_with_var var_opt;
    success
  | Instance (var1_opt, var2_opt) ->
    (if !verbose then
    Printf.printf "[Adding moduleinst %s...]\n" (Option.fold ~none:"[_]" ~some:(fun var -> var.it) var1_opt));
    Modules.find (Modules.get_module_name var2_opt)
    (* |> Backend_animation.Construct.il_of_module *)
    |> Backend_animation.Construct_v_new.vl_of_module
    |> ocaml_of_module_
    |> instantiate_helper |> fst
    |> Register.add_with_var var1_opt;
    success
  | Register (modulename, var_opt) ->
    let moduleinst = Register.find (Register.get_module_name var_opt) in
    Register.add (Util.Utf8.encode modulename) moduleinst;
    pass
  | Action a ->
    ignore (run_action a); success
  | Assertion a -> test_assertion a
  | Meta _ -> pass
  | _ -> failwith "Command not implemented :("
  end in 
  res, Sys.time () -. start_time)
  with
  | Failure msg ->
    Printexc.print_backtrace oc; 
    Printf.printf "unexpected Failure :O\n %s\n" msg; 
    fail, Sys.time () -. start_time
  | e -> 
    Printexc.print_backtrace oc; 
    Printf.printf "unexpected Exception :(\n %s\n" (Printexc.to_string e); fail, Sys.time () -. start_time

let run_wast oc cmds = 
  (* initialise spectest and meta-interpreter Store / Registry *)
  Backend_animation.State_v.Store.init ();
  Backend_animation.Runner.Register_v.init ();
  Backend_animation.State_v.HostState.reset_glb_timestamp ();
  Backend_animation.Runner.Register_v.add "spectest" Backend_animation.Runner.spectest_v;

  (* initialise ocaml store and registry *)
  globalstore := ocaml_store;
  Register.init();
  Register.add "spectest" ocaml_spectest;

  List.map (run_command oc) cmds


let tests = ref []
let srcs = ref []

let () =
  let tests, srcs = Backend_animation.Runner.parse_args () in

  (* initialise meta-interpreter and test files *)
  (* todo: meta-interpeter initialisation may no longer needed. test without. *)
  Backend_animation.Runner.init_pipeline srcs;

  let results = List.map (fun testfile ->
    let cmds = Backend_animation.Runner.run testfile in (* parsing *)
    let oc = open_out "exception.log" in
    let result = run_wast oc cmds 
      |> Backend_animation.Main_interpret.sum_results_with_time in
    print_runner_result testfile result;
    result
  ) tests in
  let total = Backend_animation.Main_interpret.sum_results_with_time
    (List.concat_map (fun (r, t) -> [(r, t)]) results) in
  Printf.printf "Warning: %d AssertInvalids were skipped.\n" !invalids;
  print_runner_result "Total" total