set_option linter.unusedVariables false

/- ============================================================
   ToyCallIndirect.lean

   Demonstrates two encodings of call_indirect_trap from the
   WebAssembly 2.0 spec, as generated by the SpecTec Lean backend.

   PART 1 – Shared Wasm types
     Verbatim from test_spectec_output.lean (new backend) unless
     marked with ★ (stub/simplification).
   PART 2 – New backend (namespace NewBackend)
     Lines 8090-8199 of test_spectec_output.lean.  NOT MODIFIED.
   PART 3 – Old backend (namespace OldBackend)
     Lines 6526-6540 of src/temp_zy_dev/wasm2.0.lean.
     MODIFIED for Lean 4 compatibility; every change is marked ★.
   PART 4 – Comparison proofs
   ============================================================ -/


-- ═══════════════════════════════════════════════════════
-- PART 1 – SHARED WASM TYPES
-- ═══════════════════════════════════════════════════════

-- ── Preamble utilities (verbatim, lines 13-23) ──────────

-- Forall: "for all elements of a list, the predicate holds"
def Forall {α₁ : Type} (P : α₁ → Prop) (xs₁ : List α₁) : Prop :=
  ∀ t_elem ∈ xs₁, P t_elem

-- Forall₂: pairwise predicate over two lists (zip-based)
def Forall₂ {α₁ α₂ : Type} (P : α₁ → α₂ → Prop) (xs₁ : List α₁) (xs₂ : List α₂) : Prop :=
  ∀ t ∈ xs₁ |>.zip xs₂, P (t.1) (t.2)

-- Map: functional map (alias for List.map; the spec uses it explicitly)
def Map {α₁ β : Type} (f : α₁ → β) (xs₁ : List α₁) : List β :=
  xs₁ |>.map f

-- ── Meta types (verbatim, lines 34-44) ──────────────────

-- r_MUT: the "mut" qualifier in Wasm types (mutable vs immutable)
inductive r_MUT : Type where
  | MUT : r_MUT
deriving Inhabited, BEq

-- N, n, m: natural number meta-variables used in the spec
-- (e.g., "iN" means "N-bit integer type")
abbrev N : Type := Nat
abbrev n : Type := Nat
abbrev m : Type := Nat

-- ── list wrapper (verbatim, lines 101-107) ───────────────
-- The SpecTec spec uses a custom "list" newtype distinct from Lean's List.
-- resulttype = list valtype means "a spec-level list of valtypes".
-- proj_list_0 unwraps it to a Lean List.
inductive list (X : Type) : Type where
  | mk_list (X_lst : List X) : list X
deriving Inhabited, BEq

def proj_list_0 (X : Type) (x : list X) : List X :=
  match x with
  | list.mk_list v_X_list_0 => (v_X_list_0)

-- ── Byte (verbatim, lines 119-125) ───────────────────────
-- Individual bytes (used by memories, data segments, names).
-- Not accessed by call_indirect, but needed by name → exportinst → moduleinst.
inductive byte : Type where
  | mk_byte (i : Nat) : byte
deriving Inhabited, BEq

-- ── uN: unsigned N-bit integer (verbatim, lines 133-139) ─
-- This is the backbone of all Wasm integer types.
-- iN is the same representation (the "signed" interpretation is semantic, not structural).
inductive uN : Type where
  | mk_uN (i : Nat) : uN
deriving Inhabited, BEq

-- proj_uN_0: extract the underlying Nat from a uN value.
-- Used in call_indirect to convert the table index i to a Nat for List indexing.
def proj_uN_0 (x : uN) : Nat :=
  match x with
  | uN.mk_uN v_num_0 => (v_num_0)

-- Aliases: iN (integer), u8, u32, u64 are all just uN with different intended widths.
abbrev iN : Type := uN
abbrev u8 : Type := uN
abbrev u32 : Type := uN
abbrev u64 : Type := uN

-- ★ STUB: fN (float) has a complex IEEE 754 encoding in the real backend.
-- call_indirect only uses i32 values, so float types are irrelevant here.
-- We use uN as a stand-in so num_ type-checks.
abbrev vN : Type := iN
abbrev vec_ : Type := vN   -- ★ stub: 128-bit SIMD vectors
abbrev fN : Type := uN     -- ★ stub: IEEE 754 floats

-- ★ STUB: func is the AST of a WebAssembly function body (instr list + locals).
-- funcinst.CODE : func, but call_indirect never inspects CODE.
abbrev func : Type := Unit

-- ── char (verbatim, lines 264-266) ───────────────────────
-- The spec's char type (Unicode codepoint); used by name.
inductive char : Type where
  | mk_char (i : Nat) : char
deriving Inhabited, BEq

-- ── Wasm value types (verbatim, lines 345-414) ───────────

-- numtype: classifies numeric values (i32, i64, f32, f64)
inductive numtype : Type where
  | I32 | I64 | F32 | F64
deriving Inhabited, BEq

-- vectype: classifies SIMD vector values
inductive vectype : Type where
  | V128 : vectype
deriving Inhabited, BEq

-- reftype: classifies reference values (function refs or host object refs)
inductive reftype : Type where
  | FUNCREF | EXTERNREF
deriving Inhabited, BEq

-- valtype: the full set of Wasm value types
inductive valtype : Type where
  | I32 | I64 | F32 | F64 | V128 | FUNCREF | EXTERNREF | BOT
deriving Inhabited, BEq

-- Inn: integer number type (just I32 or I64; excludes floats)
inductive Inn : Type where
  | I32 | I64
deriving Inhabited, BEq

def numtype_Inn (var_0 : Inn) : numtype :=
  match var_0 with | Inn.I32 => numtype.I32 | Inn.I64 => numtype.I64

def valtype_Inn (var_0 : Inn) : valtype :=
  match var_0 with | Inn.I32 => valtype.I32 | Inn.I64 => valtype.I64

-- Fnn: float number type
inductive Fnn : Type where
  | F32 | F64
deriving Inhabited, BEq

def numtype_Fnn (var_0 : Fnn) : numtype :=
  match var_0 with | Fnn.F32 => numtype.F32 | Fnn.F64 => numtype.F64

-- resulttype: a Wasm result type = (spec-level) list of value types
-- e.g., [I32, I64] means "function returns an i32 followed by an i64"
abbrev resulttype : Type := list valtype

-- ── Wasm type constructors (verbatim, lines 491-511) ─────

-- limits: {min, max?} — describes the size bounds of a table or memory
inductive limits : Type where
  | mk_limits (v_u32 : u32) (u32_opt : Option u32) : limits
deriving Inhabited, BEq

-- functype: the type of a Wasm function (params → results)
inductive functype : Type where
  | mk_functype (v_resulttype_0 : resulttype) (v_resulttype_1 : resulttype) : functype
deriving Inhabited, BEq

-- tabletype: type of a Wasm table (size limits + what kind of refs it holds)
inductive tabletype : Type where
  | mk_tabletype (v_limits : limits) (v_reftype : reftype) : tabletype
deriving Inhabited, BEq

-- ── num_: a concrete runtime numeric value (verbatim, lines 651-671) ──
-- num_ is what actually sits on the Wasm stack or in a local variable.
-- mk_num__0: an integer value, tagged with its Inn type (I32 or I64)
-- mk_num__1: a float value (★ fN is stubbed above)
inductive num_ : Type where
  | mk_num__0 (v_Inn : Inn) (var_x : iN) : num_
  | mk_num__1 (v_Fnn : Fnn) (var_x : fN) : num_
deriving Inhabited, BEq

-- proj_num__0: if the value is an integer (mk_num__0), returns its payload.
-- Returns none for floats. Used in call_indirect to extract the table index.
def proj_num__0 (var_x : num_) : Option iN :=
  match var_x with
  | num_.mk_num__0 v_Inn var_x => some var_x
  | _ => none

-- wf_uN: a uN is well-formed for N bits iff 0 ≤ i ≤ 2^N-1 (verbatim, lines 141-144)
-- (needed by wf_num_ below; wf_num_ is needed by the old backend's trap rule)
inductive wf_uN : N → uN → Prop where
  | uN_case_0 (v_N : N) (i : Nat) :
    (i ≥ 0) && (i ≤ (Int.toNat (((2 ^ v_N) : Int) - (1 : Int)))) →
    wf_uN v_N (uN.mk_uN i)

-- ★ wf_num_: axiomatized to avoid pulling in IEEE 754 float wf machinery.
-- In the real backend (lines 656-665), wf_num_ checks that a num_ value
-- is a valid representation of the given numtype (right bit-width, etc.).
-- The old backend's call_indirect_trap has wf_num_ I32 i as a premise,
-- but the proof of trap doesn't actually USE the wf content, so axiomatizing is fine.
opaque wf_num_ : numtype → num_ → Prop

-- ── Address types (verbatim, lines 5566-5580) ────────────
-- Addresses are Nat-valued indices into the store.
abbrev addr : Type := Nat
abbrev funcaddr : Type := addr
abbrev globaladdr : Type := addr
abbrev tableaddr : Type := addr
abbrev memaddr : Type := addr
abbrev elemaddr : Type := addr
abbrev dataaddr : Type := addr
abbrev hostaddr : Type := addr

-- ── ref: reference values (verbatim, lines 5610-5613) ────
-- REF_NULL: a null reference of the given type
-- REF_FUNC_ADDR a: a reference to store.FUNCS[a]
-- REF_HOST_ADDR a: a reference to a host object
inductive ref : Type where
  | REF_NULL (v_reftype : reftype) : ref
  | REF_FUNC_ADDR (v_funcaddr : funcaddr) : ref
  | REF_HOST_ADDR (v_hostaddr : hostaddr) : ref
deriving Inhabited, BEq

-- ── val: any Wasm value (verbatim, lines 5616-5622) ──────
inductive val : Type where
  | CONST (v_numtype : numtype) (_ : num_) : val
  | VCONST (v_vectype : vectype) (_ : vec_) : val
  | REF_NULL (v_reftype : reftype) : val
  | REF_FUNC_ADDR (v_funcaddr : funcaddr) : val
  | REF_HOST_ADDR (v_hostaddr : hostaddr) : val
deriving Inhabited, BEq

-- ── Identifiers (verbatim, lines 323-339) ────────────────
-- All indices are just u32 (= uN) with different semantic roles.
abbrev idx : Type := u32
abbrev typeidx : Type := idx
abbrev funcidx : Type := idx
abbrev globalidx : Type := idx
abbrev tableidx : Type := idx
abbrev elemidx : Type := idx
abbrev dataidx : Type := idx
abbrev localidx : Type := idx
abbrev labelidx : Type := idx

-- ── Module instances and store components ────────────────

-- name: a Wasm export/import name (list of Unicode chars)
-- (verbatim, lines 307-309)
inductive name : Type where
  | mk_name (char_lst : List char) : name
deriving Inhabited, BEq

-- externaddr: a store address tagged by what it points to
inductive externaddr : Type where
  | FUNC (v_funcaddr : funcaddr) : externaddr
  | GLOBAL (v_globaladdr : globaladdr) : externaddr
  | TABLE (v_tableaddr : tableaddr) : externaddr
  | MEM (v_memaddr : memaddr) : externaddr
deriving Inhabited, BEq

-- exportinst: a resolved module export (name → store address)
-- (verbatim, lines 5655-5659)
structure exportinst where
  MKexportinst ::
  NAME : name
  ADDR : externaddr
deriving Inhabited, BEq

-- moduleinst: the runtime image of a Wasm module.
-- TYPES: the type table (functype[])
-- FUNCS: funcaddr[] — resolved function addresses in the store
-- TABLES: tableaddr[] — resolved table addresses in the store
-- (verbatim, lines 5670-5680)
structure moduleinst where
  MKmoduleinst ::
  TYPES   : List functype
  FUNCS   : List funcaddr
  GLOBALS : List globaladdr
  TABLES  : List tableaddr
  MEMS    : List memaddr
  ELEMS   : List elemaddr
  DATAS   : List dataaddr
  EXPORTS : List exportinst
deriving Inhabited, BEq

-- funcinst: a function instance in the store.
-- TYPE:   the function's type signature
-- MODULE: the module where this function was defined (used to resolve type indices)
-- CODE:   the function body (★ stubbed as Unit; call_indirect never inspects it)
-- (verbatim structure, lines 5697-5702; CODE field type is stubbed)
structure funcinst where
  MKfuncinst ::
  TYPE   : functype
  MODULE : moduleinst
  CODE   : func        -- ★ func = Unit (stub)
deriving Inhabited, BEq

-- tableinst: a table in the store.
-- TYPE: table type (limits + reftype)
-- REFS: the actual table contents — a list of ref values.
-- call_indirect indexes into REFS to find which function to call.
-- (verbatim, lines 5730-5734)
structure tableinst where
  MKtableinst ::
  TYPE : tabletype
  REFS : List ref
deriving Inhabited, BEq

-- ★ STUBS: the remaining store component types.
-- globalinst, meminst, eleminst, datainst exist in the store
-- but are never accessed by call_indirect, so we stub them as Unit.
abbrev globalinst : Type := Unit
abbrev meminst    : Type := Unit
abbrev eleminst   : Type := Unit
abbrev datainst   : Type := Unit

-- store: the global Wasm runtime heap.
-- Everything that can be mutated at runtime lives here.
-- (verbatim, lines 5780-5788; stubbed fields noted above)
structure store where
  MKstore ::
  FUNCS   : List funcinst
  GLOBALS : List globalinst  -- ★ = List Unit
  TABLES  : List tableinst
  MEMS    : List meminst     -- ★ = List Unit
  ELEMS   : List eleminst    -- ★ = List Unit
  DATAS   : List datainst    -- ★ = List Unit
deriving Inhabited, BEq

-- frame: the current call activation.
-- LOCALS: local variable values
-- MODULE: which module instance this frame belongs to
-- (verbatim, lines 5807-5811)
structure frame where
  MKframe ::
  LOCALS : List val
  MODULE : moduleinst
deriving Inhabited, BEq

-- state: full Wasm machine state = (store, frame)
-- (verbatim, lines 5823-5825)
inductive state : Type where
  | mk_state (v_store : store) (v_frame : frame) : state
deriving Inhabited, BEq

-- ── admininstr: ★ SIMPLIFIED ─────────────────────────────
-- The real type has 60+ constructors (lines 5834-5909).
-- We include only the 4 used in call_indirect rules.
--
-- "Administrative instructions" are Wasm instructions extended with
-- meta-instructions that appear only in the operational semantics,
-- not in actual Wasm bytecode.
inductive admininstr : Type where
  -- CONST: push a constant onto the stack (e.g., "i32.const 5")
  -- In call_indirect, we always see (CONST I32 i) before CALL_INDIRECT.
  | CONST (v_numtype : numtype) (_ : num_) : admininstr
  -- CALL_INDIRECT x y: "call table[i] if it has type y"
  --   x = table index, y = expected type index
  | CALL_INDIRECT (v_tableidx : tableidx) (v_typeidx : typeidx) : admininstr
  -- CALL_ADDR a: internal — "call store.FUNCS[a]"
  --   This is the instruction PRODUCED by a successful call_indirect step.
  | CALL_ADDR (v_funcaddr : funcaddr) : admininstr
  -- TRAP: runtime error (produced by a failed call_indirect step)
  | TRAP : admininstr
deriving Inhabited, BEq

-- config: the thing the step relation acts on.
-- = (state, list of pending admin instructions)
-- (verbatim, lines 6221-6223)
inductive config : Type where
  | mk_config (v_state : state) (admininstr_lst : List admininstr) : config
deriving Inhabited, BEq

-- ── Accessor functions (verbatim, lines 6319-6427) ───────

-- Extract all function instances from the store
def fun_funcinst (v_state : state) : List funcinst :=
  match v_state with
  | state.mk_state s f => s.FUNCS

-- Get the function type at index y in the CURRENT frame's module type table.
-- call_indirect uses this to check if table[i].TYPE == fun_type(z, y).
def fun_type (v_state : state) (v_typeidx : typeidx) : functype :=
  match v_state with
  | state.mk_state s f => (f.MODULE.TYPES)[proj_uN_0 v_typeidx]!

-- Get the table at index x (resolves through module's TABLES list).
-- Step 1: frame.MODULE.TABLES[x] → tableaddr (an index into s.TABLES)
-- Step 2: s.TABLES[tableaddr] → tableinst
-- call_indirect indexes into .REFS on this tableinst.
def fun_table (v_state : state) (v_tableidx : tableidx) : tableinst :=
  match v_state with
  | state.mk_state s f => (s.TABLES)[(f.MODULE.TABLES)[proj_uN_0 v_tableidx]!]!


-- ═══════════════════════════════════════════════════════
-- PART 2 – NEW BACKEND
-- Source: spectec/test-lean-backend/test_spectec_output.lean
-- Lines 8090–8199. NOT MODIFIED.
-- ═══════════════════════════════════════════════════════

namespace NewBackend

/-
  call_indirect semantics (Wasm 2.0 spec §4.4.8.7):

    Given:  z  = current state
            i  = value popped from the stack (must be an i32)
            x  = table index (which table to look up)
            y  = type index (expected function type)

    The spec says:
      Let a = REFS[proj_uN_0 i]   (table lookup)
      If  a = REF_FUNC_ADDR addr
          AND funcinst[addr].TYPE = fun_type(y)
      →   [CALL_ADDR addr]         (call the function)
      -- otherwise
      →   [TRAP]

  The new backend encodes "-- otherwise" as:
      ¬ Step_read_before_call_indirect_trap (this config)

  This is the COMPLEMENT ENCODING: TRAP fires when the success
  predicate (defined as a separate inductive) does NOT hold.
-/

/-- The "success predicate": this holds iff call_indirect WOULD succeed
    (would produce CALL_ADDR a for some a, rather than TRAP).

    It's an auxiliary inductive used ONLY to define when the trap fires.

    The single constructor captures all 5 success conditions:
      h1: index i is in bounds for table x
      h2: i is actually an integer value (not a float)
      h3: REFS[i] points to function at address a
      h4: address a is valid in the store
      h5: the type of funcinst[a] matches the expected type y

    NOTE: a is an EXISTENTIAL witness here — the constructor introduces a.
    When you have h : Step_read_before_call_indirect_trap cfg,
    Lean hands you a specific a along with all 5 conditions.
    To REFUTE h (prove ¬ h), you get to assume a exists with all 5 conditions
    and must derive False. -/
inductive Step_read_before_call_indirect_trap : config → Prop where
  | call_indirect_call_0 (z : state) (i : num_) (x : idx) (y : idx) (a : addr) :
    (proj_uN_0 (Option.get! (proj_num__0 i))) < (List.length ((fun_table z x).REFS)) →
    (proj_num__0 i) != none →
    (((fun_table z x).REFS)[proj_uN_0 (Option.get! (proj_num__0 i))]!) == (ref.REF_FUNC_ADDR a) →
    a < (List.length (fun_funcinst z)) →
    (fun_type z y) == (((fun_funcinst z)[a]!).TYPE) →
    Step_read_before_call_indirect_trap
        (config.mk_config z [admininstr.CONST numtype.I32 i, admininstr.CALL_INDIRECT x y])

/-- Step_read: the single-step reduction relation.
    We include only the call_indirect rules; the full inductive has ~60 constructors. -/
inductive Step_read : config → List admininstr → Prop where
  /-- call_indirect_call: all 5 success conditions hold → reduce to CALL_ADDR a -/
  | call_indirect_call (z : state) (i : num_) (x : idx) (y : idx) (a : addr) :
      (proj_uN_0 (Option.get! (proj_num__0 i))) < (List.length ((fun_table z x).REFS)) →
      (proj_num__0 i) != none →
      (((fun_table z x).REFS)[proj_uN_0 (Option.get! (proj_num__0 i))]!) == (ref.REF_FUNC_ADDR a) →
      a < (List.length (fun_funcinst z)) →
      (fun_type z y) == (((fun_funcinst z)[a]!).TYPE) →
      Step_read (config.mk_config z [admininstr.CONST numtype.I32 i, admininstr.CALL_INDIRECT x y])
                [admininstr.CALL_ADDR a]
  /-- call_indirect_trap: success conditions do NOT hold → TRAP

      Key: the only premise is ¬ Step_read_before_call_indirect_trap.
      This single negation covers ALL failure modes:
        - out-of-bounds index  (h1 fails)
        - not an integer value (h2 fails)
        - null or host ref     (h3 fails)
        - no such function     (h4 fails)
        - type mismatch        (h5 fails)
      No matter which fails, the negation holds, and TRAP fires. -/
  | call_indirect_trap (z : state) (i : num_) (x : idx) (y : idx) :
      ¬ Step_read_before_call_indirect_trap
            (config.mk_config z [admininstr.CONST numtype.I32 i, admininstr.CALL_INDIRECT x y]) →
      Step_read (config.mk_config z [admininstr.CONST numtype.I32 i, admininstr.CALL_INDIRECT x y])
                [admininstr.TRAP]

-- ───────────────────────────────────────────────────────
-- THEOREM 1 (New): Empty table → TRAP
-- ───────────────────────────────────────────────────────

/-- If the table at index x has NO entries, any call_indirect traps.

    Big picture: An empty table can't satisfy h1 (the index i is in bounds)
    because List.length [] = 0 and n < 0 is impossible for Nat.
    So the success predicate is definitively false, and the trap rule fires.

    This is a clean, unconditional proof — no extra hypotheses about i or a
    are needed. -/
theorem empty_table_always_traps
    (z : state) (i : num_) (x y : idx)
    (hempty : (fun_table z x).REFS = []) :
    Step_read (config.mk_config z [admininstr.CONST numtype.I32 i, admininstr.CALL_INDIRECT x y])
              [admininstr.TRAP] := by
  -- Apply the trap rule. Its sole premise is ¬ Step_read_before_call_indirect_trap.
  apply Step_read.call_indirect_trap
  -- Goal: ¬ Step_read_before_call_indirect_trap (config.mk_config z [...])
  -- Unfold the negation: assume it holds, derive False.
  intro h
  -- h : Step_read_before_call_indirect_trap (config.mk_config z [...])
  -- Case-split: the only constructor is call_indirect_call_0.
  -- After cases, Lean injects equalities unifying the constructor's config
  -- with ours, leaving h1..h5 mentioning our z, i, x, y directly.
  cases h with
  | call_indirect_call_0 _ _ _ _ _ h1 _ _ _ _ =>
    -- h1 : proj_uN_0 (Option.get! (proj_num__0 i)) < List.length ((fun_table z x).REFS)
    -- Rewrite with hempty: (fun_table z x).REFS = []
    simp only [hempty, List.length_nil] at h1
    -- h1 is now: proj_uN_0 (...) < 0
    -- For Nat, n < 0 is always False. omega closes the goal.
    omega

-- ───────────────────────────────────────────────────────
-- THEOREM 2 (New): Progress — call_indirect never gets stuck
-- ───────────────────────────────────────────────────────

/-- For ANY state z and ANY value i, the call_indirect instruction either:
      (a) steps to [CALL_ADDR a]  for some specific address a, OR
      (b) steps to [TRAP]

    There is no "stuck" configuration where neither applies.

    This is the PROGRESS property for call_indirect.
    The new backend's complement encoding makes this immediately provable
    via classical excluded middle on the success predicate. -/
theorem call_indirect_progress
    (z : state) (i : num_) (x y : idx) :
    (∃ a : addr,
       Step_read (config.mk_config z [admininstr.CONST numtype.I32 i, admininstr.CALL_INDIRECT x y])
                 [admininstr.CALL_ADDR a])
    ∨
    Step_read (config.mk_config z [admininstr.CONST numtype.I32 i, admininstr.CALL_INDIRECT x y])
              [admininstr.TRAP] := by
  -- Classical excluded middle: either the success predicate holds or it doesn't.
  -- In classical logic, for any P, we have P ∨ ¬P.
  by_cases h : Step_read_before_call_indirect_trap
      (config.mk_config z [admininstr.CONST numtype.I32 i, admininstr.CALL_INDIRECT x y])
  · -- Case 1: h says the call WOULD succeed for some specific a.
    left
    -- Destructure h to get the address a and all 5 premises.
    cases h with
    | call_indirect_call_0 _ _ _ _ a h1 h2 h3 h4 h5 =>
      -- a is now known. Lean unified the z/i/x/y from the constructor
      -- with the outer z/i/x/y, so we use them directly (via underscores).
      exact ⟨a, Step_read.call_indirect_call z i x y a h1 h2 h3 h4 h5⟩
  · -- Case 2: h : ¬ Step_read_before_call_indirect_trap (config)
    --   The success predicate definitively does NOT hold.
    right
    -- Apply the trap rule with h as its only premise.
    exact Step_read.call_indirect_trap z i x y h

end NewBackend


-- ═══════════════════════════════════════════════════════
-- PART 3 – OLD BACKEND
-- Source: spectec/src/temp_zy_dev/wasm2.0.lean
-- Lines 6526–6540.
-- MODIFIED for Lean 4 and shared types. Every change marked ★.
-- ═══════════════════════════════════════════════════════

namespace OldBackend

/-
  The old backend encodes the same spec rule differently.

  call_indirect_trap (OLD) requires:
    (1) i IS in bounds: proj_uN_0 i < List.length REFS   ← KEY DIFFERENCE
    (2) i is an integer value
    (3) caller provides a specific a with a < |funcinst|  ← KEY DIFFERENCE
    (4) REFS[i] ≠ REF_FUNC_ADDR a  OR  type mismatch
    (5) wf_num_ I32 i

  Contrast with new backend (call_indirect_trap):
    Only premise: ¬ Step_read_before_call_indirect_trap (the config)

  GAPS in the old encoding:
    GAP 1 (out-of-bounds trap): When REFS = [] or i ≥ |REFS|, premise (1) fails.
      The config is STUCK: neither call nor trap rule applies.
      The Wasm spec says this should trap. The old backend cannot prove it.

    GAP 2 (witness burden): Premise (3) requires the caller to provide a
      SPECIFIC a that is in-bounds for funcinst. This means:
      (a) If there are no functions in the store, (3) is unprovable.
      (b) In proofs, you must "invent" an a, but the choice of a may be
          arbitrary and not connected to what REFS[i] actually contains.
      The new backend resolves both by using ¬ Step_read_before_...,
      which lets Lean provide a hypothetical a via cases and you refute it.
-/

inductive Step_read : config → List admininstr → Prop where
  -- call_indirect_call: all conditions hold → call the function
  -- ★ Modified: Lean 3 "forall (z : state) ... ->" → Lean 4 named args
  -- ★ Modified: ".CONST .I32" → "admininstr.CONST numtype.I32" (explicit namespace)
  -- ★ Modified: ".CALL_INDIRECT x y" → "admininstr.CALL_INDIRECT x y"
  -- ★ Modified: ".CALL_ADDR a" → "admininstr.CALL_ADDR a"
  -- ★ Modified: wf_num_ added after other premises (was 1st in original; order is logically equivalent)
  | call_indirect_call (z : state) (i : num_) (x : idx) (y : idx) (a : addr) :
      (proj_uN_0 (Option.get! (proj_num__0 i))) < (List.length ((fun_table z x).REFS)) →
      (proj_num__0 i) != none →
      (((fun_table z x).REFS)[proj_uN_0 (Option.get! (proj_num__0 i))]!) == (ref.REF_FUNC_ADDR a) →
      (a < (List.length (fun_funcinst z))) →
      ((fun_type z y) == (((fun_funcinst z)[a]!).TYPE)) →
      wf_num_ numtype.I32 i →  -- ★ wf_num_ is opaque (axiomatized above)
      Step_read (config.mk_config z [admininstr.CONST numtype.I32 i, admininstr.CALL_INDIRECT x y])
                [admininstr.CALL_ADDR a]

  -- call_indirect_trap: in-bounds BUT mismatch → TRAP
  -- ★ Same syntax modifications as call above.
  -- ★ CRITICAL: premise (1) below requires i to be IN BOUNDS.
  --   This makes the rule INAPPLICABLE when i ≥ |REFS|, including when REFS = [].
  | call_indirect_trap (z : state) (i : num_) (x : idx) (y : idx) (a : addr) :
      -- (1) ← THE PROBLEMATIC PREMISE: i must be in bounds for REFS.
      --   Consequence: out-of-bounds index cannot trigger this trap rule.
      (proj_uN_0 (Option.get! (proj_num__0 i))) < (List.length ((fun_table z x).REFS)) →
      -- (2) i must be an integer value (not a float)
      (proj_num__0 i) != none →
      -- (3) ← REQUIRES CALLER-SUPPLIED 'a': a must be a valid funcinst address.
      --   The trap fires NOT because a is wrong, but because REFS[i] doesn't
      --   match a OR the type doesn't match. But a still has to be "valid".
      (a < (List.length (fun_funcinst z))) →
      -- (4) The failure: either the table entry isn't a function ref to a,
      --   or it IS but the type is wrong.
      -- ★ Note: || here is BEq-level boolean OR (not propositional ∨).
      --   In the original old backend: the same || was used.
      (   (((fun_table z x).REFS)[proj_uN_0 (Option.get! (proj_num__0 i))]! != (ref.REF_FUNC_ADDR a))
       || ((fun_type z y) != (((fun_funcinst z)[a]!).TYPE))   ) →
      -- (5) i is a well-formed i32 value
      wf_num_ numtype.I32 i →
      Step_read (config.mk_config z [admininstr.CONST numtype.I32 i, admininstr.CALL_INDIRECT x y])
                [admininstr.TRAP]

-- ───────────────────────────────────────────────────────
-- THEOREM ATTEMPT 1 (Old): Empty table → TRAP
-- ───────────────────────────────────────────────────────

/-- ATTEMPT: If the table is empty, call_indirect traps.

    This theorem CANNOT be proved with the old backend's rules.

    To apply call_indirect_trap, we need premise (1):
      proj_uN_0 (...) < List.length (fun_table z x).REFS
    With hempty: REFS = [], this becomes:
      proj_uN_0 (...) < List.length []
      = proj_uN_0 (...) < 0
    This is FALSE for any Nat. No applicable rule exists.

    THE CONFIG IS STUCK. The old backend cannot derive [TRAP] for an
    empty table, even though the Wasm spec clearly requires a trap.

    This is GAP 1 of the old backend.
    We mark it sorry to document the genuine incompleteness. -/
theorem empty_table_stuck_old
    (z : state) (i : num_) (x y : idx)
    (hempty : (fun_table z x).REFS = []) :
    Step_read (config.mk_config z [admininstr.CONST numtype.I32 i, admininstr.CALL_INDIRECT x y])
              [admininstr.TRAP] := by
  apply Step_read.call_indirect_trap
  simp only [hempty, List.length_nil]
  

  -- To proceed, we would need to apply call_indirect_trap.
  -- That requires supplying a specific address 'a' and proving premise (1).
  -- Premise (1): proj_uN_0 (...) < List.length []  =  n < 0
  -- This is False for Nat. There is no valid proof.
  --
  -- Neither call_indirect_call nor call_indirect_trap can fire here.
  -- The old backend has no rule for out-of-bounds trap.
  sorry  -- ← GENUINE GAP: the old encoding is incomplete for this case

-- ───────────────────────────────────────────────────────
-- THEOREM ATTEMPT 2 (Old): Progress
-- ───────────────────────────────────────────────────────

/-- ATTEMPT: Progress for call_indirect under the old backend.

    Also CANNOT be proved. The stuck-state example above (empty table)
    is a concrete witness against progress: for REFS = [], neither
    [CALL_ADDR a] nor [TRAP] is derivable.

    The new backend avoids this by having call_indirect_trap require
    only ¬ Step_read_before_call_indirect_trap, which is trivially
    satisfied when REFS = [] (since h1 fails). -/
theorem call_indirect_progress_old
    (z : state) (i : num_) (x y : idx) :
    (∃ a : addr,
       Step_read (config.mk_config z [admininstr.CONST numtype.I32 i, admininstr.CALL_INDIRECT x y])
                 [admininstr.CALL_ADDR a])
    ∨
    Step_read (config.mk_config z [admininstr.CONST numtype.I32 i, admininstr.CALL_INDIRECT x y])
              [admininstr.TRAP] := by
  -- We would need to split on whether REFS is empty or not,
  -- and whether i is in bounds. But the old backend has no trap rule
  -- for the out-of-bounds case, so the right disjunct is unprovable
  -- without extra hypotheses.
  sorry  -- ← Old backend cannot prove this in general

-- ───────────────────────────────────────────────────────
-- THEOREM 3 (Old): What the old backend CAN prove
-- ───────────────────────────────────────────────────────

/-- The old backend CAN prove trap when the caller explicitly supplies:
      - a specific address 'a'
      - proof that i IS in bounds
      - proof that a IS a valid function index
      - proof of a mismatch (bad ref or type mismatch)
      - proof that i is a well-formed i32

    Compare to the new backend:
      Call `Step_read.call_indirect_trap z i x y h` where h : ¬ success predicate.
      No a required. No in-bounds condition required. Just refute the success predicate.

    This shows the old backend has HIGHER PROOF BURDEN: the caller must
    provide more evidence even for a straightforward trap. -/
theorem explicit_mismatch_traps_old
    (z : state) (i : num_) (x y : idx) (a : addr)
    -- All of these must be supplied by the CALLER:
    (h_in_bounds : (proj_uN_0 (Option.get! (proj_num__0 i))) < (List.length ((fun_table z x).REFS)))
    (h_is_int    : (proj_num__0 i) != none)
    (h_a_valid   : a < (List.length (fun_funcinst z)))
    (h_mismatch  :
         (((fun_table z x).REFS)[proj_uN_0 (Option.get! (proj_num__0 i))]! != (ref.REF_FUNC_ADDR a))
      || ((fun_type z y) != (((fun_funcinst z)[a]!).TYPE)))
    (h_wf        : wf_num_ numtype.I32 i) :
    Step_read (config.mk_config z [admininstr.CONST numtype.I32 i, admininstr.CALL_INDIRECT x y])
              [admininstr.TRAP] :=
  -- Apply the constructor directly.
  Step_read.call_indirect_trap z i x y a h_in_bounds h_is_int h_a_valid h_mismatch h_wf

end OldBackend


-- ═══════════════════════════════════════════════════════
-- PART 4 – VERIFICATION
-- ═══════════════════════════════════════════════════════

-- #check confirms Lean accepted the theorem statements and types.
-- (It does NOT check sorry'd proofs are complete — they are noted as gaps.)

#check @NewBackend.Step_read_before_call_indirect_trap
-- NewBackend.Step_read_before_call_indirect_trap : config → Prop

#check @NewBackend.empty_table_always_traps
-- : ∀ (z : state) (i : num_) (x y : idx),
--     (fun_table z x).REFS = [] →
--     NewBackend.Step_read (config.mk_config z [...]) [admininstr.TRAP]

#check @NewBackend.call_indirect_progress
-- : ∀ (z : state) (i : num_) (x y : idx),
--     (∃ a, Step_read ... [CALL_ADDR a]) ∨ Step_read ... [TRAP]
-- The progress theorem: call_indirect is always productive, never stuck.

#check @OldBackend.explicit_mismatch_traps_old
-- The one theorem old backend CAN prove (with heavy caller burden).
