
name: CI for DL meta-interpreter on Wasm-3.0 features

on:
  push:
    branches: [ il-animate ]
    paths: [ spectec/**, specification/wasm-3.0/** ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  spectec-animation:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        inline:
          - "--inline"
          - ""

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5.3.x
      - name: Setup Dune
        run: opam install --yes dune menhir mdx zarith tsort
      - name: Build
        run: |
          eval $(opam env)
          cd spectec && make
      - name: Test wasm-3.0 features
        run: |
          cd spectec
          ./spectec -l ../specification/wasm-3.0/* src/backend-animation/meta.spectec --animate ${{ matrix.inline }} --new-interpreter-v \
            ./test-interpreter/spec-test-3/bulk-memory \
            ./test-interpreter/spec-test-3/exceptions \
            ./test-interpreter/spec-test-3/gc \
            ./test-interpreter/spec-test-3/relaxed-simd \
            ./test-interpreter/spec-test-3/simd \
            ./test-interpreter/spec-test-3/memory64 \
            ./test-interpreter/spec-test-3/multi-memory
