theory admininstr
(* Imported Code *)
	imports Main
	  reference_isabelle_output_wasm2
begin

(* Auxiliary Definition at: isabelle-aux.spectec:1.1-1.31 *)
function (sequential) is_val :: "admininstr ⇒ bool" where
		  "is_val (admininstr_subcase_7 (admininstr_subtype_7_REF_HOST_ADDR v_hostaddr)) = True"
		| "is_val (admininstr_subcase_7 (admininstr_subtype_7_REF_FUNC_ADDR v_funcaddr)) = True"
		| "is_val (admininstr_subcase_4 (admininstr_subtype_4_REF_NULL v_reftype)) = True"
		| "is_val (admininstr_subcase_2 (admininstr_subtype_2_VCONST v_vectype var_1)) = True"
		| "is_val (admininstr_subcase_1 (admininstr_subtype_1_CONST v_numtype var_0)) = True"
		| "is_val v_admininstr = False"
	by pat_completeness auto

(* Auxiliary Definition at: isabelle-aux.spectec:5.1-5.33 *)
function (sequential) is_instr :: "admininstr ⇒ bool" where
		  "is_instr (admininstr_subcase_7 (admininstr_subtype_7_DATA_DROP dataidx_0)) = True"
		| "is_instr (admininstr_subcase_7 (admininstr_subtype_7_MEMORY_INIT v_dataidx)) = True"
		| "is_instr (admininstr_subcase_7 admininstr_subtype_7_MEMORY_COPY) = True"
		| "is_instr (admininstr_subcase_7 admininstr_subtype_7_MEMORY_FILL) = True"
		| "is_instr (admininstr_subcase_7 admininstr_subtype_7_MEMORY_GROW) = True"
		| "is_instr (admininstr_subcase_6 admininstr_subtype_6_MEMORY_SIZE) = True"
		| "is_instr (admininstr_subcase_6 (admininstr_subtype_6_VSTORE_LANE vectype_7 sz_0 memarg_4 laneidx_2)) = True"
		| "is_instr (admininstr_subcase_6 (admininstr_subtype_6_VSTORE vectype_6 memarg_3)) = True"
		| "is_instr (admininstr_subcase_6 (admininstr_subtype_6_VLOAD_LANE vectype_5 v_sz memarg_2 laneidx_1)) = True"
		| "is_instr (admininstr_subcase_6 (admininstr_subtype_6_VLOAD vectype_4 vloadop_opt memarg_1)) = True"
		| "is_instr (admininstr_subcase_6 (admininstr_subtype_6_STORE numtype_6 sz_opt memarg_0)) = True"
		| "is_instr (admininstr_subcase_6 (admininstr_subtype_6_LOAD numtype_5 var_13 v_memarg)) = True"
		| "is_instr (admininstr_subcase_6 (admininstr_subtype_6_ELEM_DROP elemidx_0)) = True"
		| "is_instr (admininstr_subcase_6 (admininstr_subtype_6_TABLE_INIT tableidx_7 v_elemidx)) = True"
		| "is_instr (admininstr_subcase_5 (admininstr_subtype_5_TABLE_COPY tableidx_5 tableidx_6)) = True"
		| "is_instr (admininstr_subcase_5 (admininstr_subtype_5_TABLE_FILL tableidx_4)) = True"
		| "is_instr (admininstr_subcase_5 (admininstr_subtype_5_TABLE_GROW tableidx_3)) = True"
		| "is_instr (admininstr_subcase_5 (admininstr_subtype_5_TABLE_SIZE tableidx_2)) = True"
		| "is_instr (admininstr_subcase_5 (admininstr_subtype_5_TABLE_SET tableidx_1)) = True"
		| "is_instr (admininstr_subcase_5 (admininstr_subtype_5_TABLE_GET tableidx_0)) = True"
		| "is_instr (admininstr_subcase_5 (admininstr_subtype_5_GLOBAL_SET globalidx_0)) = True"
		| "is_instr (admininstr_subcase_5 (admininstr_subtype_5_GLOBAL_GET v_globalidx)) = True"
		| "is_instr (admininstr_subcase_5 (admininstr_subtype_5_LOCAL_TEE localidx_1)) = True"
		| "is_instr (admininstr_subcase_4 (admininstr_subtype_4_LOCAL_SET localidx_0)) = True"
		| "is_instr (admininstr_subcase_4 (admininstr_subtype_4_LOCAL_GET v_localidx)) = True"
		| "is_instr (admininstr_subcase_4 admininstr_subtype_4_REF_IS_NULL) = True"
		| "is_instr (admininstr_subcase_4 (admininstr_subtype_4_REF_FUNC funcidx_0)) = True"
		| "is_instr (admininstr_subcase_4 (admininstr_subtype_4_REF_NULL v_reftype)) = True"
		| "is_instr (admininstr_subcase_4 (admininstr_subtype_4_VCVTOP shape_6 shape_7 v_vcvtop)) = True"
		| "is_instr (admininstr_subcase_4 (admininstr_subtype_4_VNARROW ishape_1_2 ishape_2_2 v_sx)) = True"
		| "is_instr (admininstr_subcase_4 (admininstr_subtype_4_VEXTBINOP ishape_1_1 ishape_2_1 var_12)) = True"
		| "is_instr (admininstr_subcase_4 (admininstr_subtype_4_VEXTUNOP ishape_1_0 ishape_2_0 var_11)) = True"
		| "is_instr (admininstr_subcase_3 (admininstr_subtype_3_VREPLACE_LANE shape_5 laneidx_0)) = True"
		| "is_instr (admininstr_subcase_3 (admininstr_subtype_3_VEXTRACT_LANE shape_4 sx_opt v_laneidx)) = True"
		| "is_instr (admininstr_subcase_3 (admininstr_subtype_3_VSPLAT shape_3)) = True"
		| "is_instr (admininstr_subcase_3 (admininstr_subtype_3_VSHUFFLE ishape_2 laneidx_lst)) = True"
		| "is_instr (admininstr_subcase_3 (admininstr_subtype_3_VSWIZZLE ishape_1)) = True"
		| "is_instr (admininstr_subcase_3 (admininstr_subtype_3_VBITMASK ishape_0)) = True"
		| "is_instr (admininstr_subcase_3 (admininstr_subtype_3_VSHIFTOP v_ishape var_10)) = True"
		| "is_instr (admininstr_subcase_3 (admininstr_subtype_3_VRELOP shape_2 var_9)) = True"
		| "is_instr (admininstr_subcase_3 (admininstr_subtype_3_VTESTOP shape_1 var_8)) = True"
		| "is_instr (admininstr_subcase_2 (admininstr_subtype_2_VBINOP shape_0 var_7)) = True"
		| "is_instr (admininstr_subcase_2 (admininstr_subtype_2_VUNOP v_shape var_6)) = True"
		| "is_instr (admininstr_subcase_2 (admininstr_subtype_2_VVTESTOP vectype_3 v_vvtestop)) = True"
		| "is_instr (admininstr_subcase_2 (admininstr_subtype_2_VVTERNOP vectype_2 v_vvternop)) = True"
		| "is_instr (admininstr_subcase_2 (admininstr_subtype_2_VVBINOP vectype_1 v_vvbinop)) = True"
		| "is_instr (admininstr_subcase_2 (admininstr_subtype_2_VVUNOP vectype_0 v_vvunop)) = True"
		| "is_instr (admininstr_subcase_2 (admininstr_subtype_2_VCONST v_vectype var_5)) = True"
		| "is_instr (admininstr_subcase_2 (admininstr_subtype_2_EXTEND numtype_4 v_n)) = True"
		| "is_instr (admininstr_subcase_2 (admininstr_subtype_2_CVTOP numtype_1_0 numtype_2_0 v_cvtop)) = True"
		| "is_instr (admininstr_subcase_1 (admininstr_subtype_1_RELOP numtype_3 var_4)) = True"
		| "is_instr (admininstr_subcase_1 (admininstr_subtype_1_TESTOP numtype_2 var_3)) = True"
		| "is_instr (admininstr_subcase_1 (admininstr_subtype_1_BINOP numtype_1 var_2)) = True"
		| "is_instr (admininstr_subcase_1 (admininstr_subtype_1_UNOP numtype_0 var_1)) = True"
		| "is_instr (admininstr_subcase_1 (admininstr_subtype_1_CONST v_numtype var_0)) = True"
		| "is_instr (admininstr_subcase_1 admininstr_subtype_1_RETURN) = True"
		| "is_instr (admininstr_subcase_1 (admininstr_subtype_1_CALL_INDIRECT v_tableidx v_typeidx)) = True"
		| "is_instr (admininstr_subcase_1 (admininstr_subtype_1_CALL v_funcidx)) = True"
		| "is_instr (admininstr_subcase_1 (admininstr_subtype_1_BR_TABLE labelidx_lst labelidx_1)) = True"
		| "is_instr (admininstr_subcase_0 (admininstr_subtype_0_BR_IF labelidx_0)) = True"
		| "is_instr (admininstr_subcase_0 (admininstr_subtype_0_BR v_labelidx)) = True"
		| "is_instr (admininstr_subcase_0 (admininstr_subtype_0_IFELSE blocktype_1 instr_lst_1 instr_lst_2)) = True"
		| "is_instr (admininstr_subcase_0 (admininstr_subtype_0_LOOP blocktype_0 instr_lst_0)) = True"
		| "is_instr (admininstr_subcase_0 (admininstr_subtype_0_BLOCK v_blocktype instr_lst)) = True"
		| "is_instr (admininstr_subcase_0 (admininstr_subtype_0_SELECT valtype_lst_opt)) = True"
		| "is_instr (admininstr_subcase_0 admininstr_subtype_0_DROP) = True"
		| "is_instr (admininstr_subcase_0 admininstr_subtype_0_UNREACHABLE) = True"
		| "is_instr (admininstr_subcase_0 admininstr_subtype_0_NOP) = True"
		| "is_instr v_admininstr = False"
	by pat_completeness auto

(* Auxiliary Definition at: isabelle-aux.spectec:9.1-9.38 *)
function (sequential) is_admininstr :: "admininstr ⇒ bool" where
		  "is_admininstr (admininstr_subcase_7 (admininstr_subtype_7_DATA_DROP dataidx_0)) = False"
		| "is_admininstr (admininstr_subcase_7 (admininstr_subtype_7_MEMORY_INIT v_dataidx)) = False"
		| "is_admininstr (admininstr_subcase_7 admininstr_subtype_7_MEMORY_COPY) = False"
		| "is_admininstr (admininstr_subcase_7 admininstr_subtype_7_MEMORY_FILL) = False"
		| "is_admininstr (admininstr_subcase_7 admininstr_subtype_7_MEMORY_GROW) = False"
		| "is_admininstr (admininstr_subcase_6 admininstr_subtype_6_MEMORY_SIZE) = False"
		| "is_admininstr (admininstr_subcase_6 (admininstr_subtype_6_VSTORE_LANE vectype_7 sz_0 memarg_4 laneidx_2)) = False"
		| "is_admininstr (admininstr_subcase_6 (admininstr_subtype_6_VSTORE vectype_6 memarg_3)) = False"
		| "is_admininstr (admininstr_subcase_6 (admininstr_subtype_6_VLOAD_LANE vectype_5 v_sz memarg_2 laneidx_1)) = False"
		| "is_admininstr (admininstr_subcase_6 (admininstr_subtype_6_VLOAD vectype_4 vloadop_opt memarg_1)) = False"
		| "is_admininstr (admininstr_subcase_6 (admininstr_subtype_6_STORE numtype_6 sz_opt memarg_0)) = False"
		| "is_admininstr (admininstr_subcase_6 (admininstr_subtype_6_LOAD numtype_5 var_13 v_memarg)) = False"
		| "is_admininstr (admininstr_subcase_6 (admininstr_subtype_6_ELEM_DROP elemidx_0)) = False"
		| "is_admininstr (admininstr_subcase_6 (admininstr_subtype_6_TABLE_INIT tableidx_7 v_elemidx)) = False"
		| "is_admininstr (admininstr_subcase_5 (admininstr_subtype_5_TABLE_COPY tableidx_5 tableidx_6)) = False"
		| "is_admininstr (admininstr_subcase_5 (admininstr_subtype_5_TABLE_FILL tableidx_4)) = False"
		| "is_admininstr (admininstr_subcase_5 (admininstr_subtype_5_TABLE_GROW tableidx_3)) = False"
		| "is_admininstr (admininstr_subcase_5 (admininstr_subtype_5_TABLE_SIZE tableidx_2)) = False"
		| "is_admininstr (admininstr_subcase_5 (admininstr_subtype_5_TABLE_SET tableidx_1)) = False"
		| "is_admininstr (admininstr_subcase_5 (admininstr_subtype_5_TABLE_GET tableidx_0)) = False"
		| "is_admininstr (admininstr_subcase_5 (admininstr_subtype_5_GLOBAL_SET globalidx_0)) = False"
		| "is_admininstr (admininstr_subcase_5 (admininstr_subtype_5_GLOBAL_GET v_globalidx)) = False"
		| "is_admininstr (admininstr_subcase_5 (admininstr_subtype_5_LOCAL_TEE localidx_1)) = False"
		| "is_admininstr (admininstr_subcase_4 (admininstr_subtype_4_LOCAL_SET localidx_0)) = False"
		| "is_admininstr (admininstr_subcase_4 (admininstr_subtype_4_LOCAL_GET v_localidx)) = False"
		| "is_admininstr (admininstr_subcase_4 admininstr_subtype_4_REF_IS_NULL) = False"
		| "is_admininstr (admininstr_subcase_4 (admininstr_subtype_4_REF_FUNC funcidx_0)) = False"
		| "is_admininstr (admininstr_subcase_4 (admininstr_subtype_4_REF_NULL v_reftype)) = False"
		| "is_admininstr (admininstr_subcase_4 (admininstr_subtype_4_VCVTOP shape_6 shape_7 v_vcvtop)) = False"
		| "is_admininstr (admininstr_subcase_4 (admininstr_subtype_4_VNARROW ishape_1_2 ishape_2_2 v_sx)) = False"
		| "is_admininstr (admininstr_subcase_4 (admininstr_subtype_4_VEXTBINOP ishape_1_1 ishape_2_1 var_12)) = False"
		| "is_admininstr (admininstr_subcase_4 (admininstr_subtype_4_VEXTUNOP ishape_1_0 ishape_2_0 var_11)) = False"
		| "is_admininstr (admininstr_subcase_3 (admininstr_subtype_3_VREPLACE_LANE shape_5 laneidx_0)) = False"
		| "is_admininstr (admininstr_subcase_3 (admininstr_subtype_3_VEXTRACT_LANE shape_4 sx_opt v_laneidx)) = False"
		| "is_admininstr (admininstr_subcase_3 (admininstr_subtype_3_VSPLAT shape_3)) = False"
		| "is_admininstr (admininstr_subcase_3 (admininstr_subtype_3_VSHUFFLE ishape_2 laneidx_lst)) = False"
		| "is_admininstr (admininstr_subcase_3 (admininstr_subtype_3_VSWIZZLE ishape_1)) = False"
		| "is_admininstr (admininstr_subcase_3 (admininstr_subtype_3_VBITMASK ishape_0)) = False"
		| "is_admininstr (admininstr_subcase_3 (admininstr_subtype_3_VSHIFTOP v_ishape var_10)) = False"
		| "is_admininstr (admininstr_subcase_3 (admininstr_subtype_3_VRELOP shape_2 var_9)) = False"
		| "is_admininstr (admininstr_subcase_3 (admininstr_subtype_3_VTESTOP shape_1 var_8)) = False"
		| "is_admininstr (admininstr_subcase_2 (admininstr_subtype_2_VBINOP shape_0 var_7)) = False"
		| "is_admininstr (admininstr_subcase_2 (admininstr_subtype_2_VUNOP v_shape var_6)) = False"
		| "is_admininstr (admininstr_subcase_2 (admininstr_subtype_2_VVTESTOP vectype_3 v_vvtestop)) = False"
		| "is_admininstr (admininstr_subcase_2 (admininstr_subtype_2_VVTERNOP vectype_2 v_vvternop)) = False"
		| "is_admininstr (admininstr_subcase_2 (admininstr_subtype_2_VVBINOP vectype_1 v_vvbinop)) = False"
		| "is_admininstr (admininstr_subcase_2 (admininstr_subtype_2_VVUNOP vectype_0 v_vvunop)) = False"
		| "is_admininstr (admininstr_subcase_2 (admininstr_subtype_2_VCONST v_vectype var_5)) = False"
		| "is_admininstr (admininstr_subcase_2 (admininstr_subtype_2_EXTEND numtype_4 v_n)) = False"
		| "is_admininstr (admininstr_subcase_2 (admininstr_subtype_2_CVTOP numtype_1_0 numtype_2_0 v_cvtop)) = False"
		| "is_admininstr (admininstr_subcase_1 (admininstr_subtype_1_RELOP numtype_3 var_4)) = False"
		| "is_admininstr (admininstr_subcase_1 (admininstr_subtype_1_TESTOP numtype_2 var_3)) = False"
		| "is_admininstr (admininstr_subcase_1 (admininstr_subtype_1_BINOP numtype_1 var_2)) = False"
		| "is_admininstr (admininstr_subcase_1 (admininstr_subtype_1_UNOP numtype_0 var_1)) = False"
		| "is_admininstr (admininstr_subcase_1 (admininstr_subtype_1_CONST v_numtype var_0)) = False"
		| "is_admininstr (admininstr_subcase_1 admininstr_subtype_1_RETURN) = False"
		| "is_admininstr (admininstr_subcase_1 (admininstr_subtype_1_CALL_INDIRECT v_tableidx v_typeidx)) = False"
		| "is_admininstr (admininstr_subcase_1 (admininstr_subtype_1_CALL v_funcidx)) = False"
		| "is_admininstr (admininstr_subcase_1 (admininstr_subtype_1_BR_TABLE labelidx_lst labelidx_1)) = False"
		| "is_admininstr (admininstr_subcase_0 (admininstr_subtype_0_BR_IF labelidx_0)) = False"
		| "is_admininstr (admininstr_subcase_0 (admininstr_subtype_0_BR v_labelidx)) = False"
		| "is_admininstr (admininstr_subcase_0 (admininstr_subtype_0_IFELSE blocktype_1 instr_lst_1 instr_lst_2)) = False"
		| "is_admininstr (admininstr_subcase_0 (admininstr_subtype_0_LOOP blocktype_0 instr_lst_0)) = False"
		| "is_admininstr (admininstr_subcase_0 (admininstr_subtype_0_BLOCK v_blocktype instr_lst)) = False"
		| "is_admininstr (admininstr_subcase_0 (admininstr_subtype_0_SELECT valtype_lst_opt)) = False"
		| "is_admininstr (admininstr_subcase_0 admininstr_subtype_0_DROP) = False"
		| "is_admininstr (admininstr_subcase_0 admininstr_subtype_0_UNREACHABLE) = False"
		| "is_admininstr (admininstr_subcase_0 admininstr_subtype_0_NOP) = False"
		| "is_admininstr v_admininstr = True"
	by pat_completeness auto

end
